<div class="login-box">
      <div class="login-logo">
        <a href="../../index2.html"><b>OSTİM</b> EKO-OSTİM  </a>
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sisteme Giriş Yapınız</p>
        <?php if(isset($this->notValidated) && $this->notValidated == true) { ?>
        <div class="alert alert-info alert-dismissable">
            
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-info"></i> Alert!</h4>
                    Info alert preview. This alert is dismissable.
                    <?php echo $this->notValidated;  ?>
                  </div>
        <?php  } ?>
        <form action="<?php echo $this->url('login'); ?>" method="post">       
          <div class="form-group has-feedback">
            <input id="eposta" name="eposta" type="email" class="form-control" placeholder="E-posta"/>
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input id="sifre" name="sifre" type="password" class="form-control" placeholder="Şifre"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> Beni Hatırla
                </label>
              </div>                        
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button id="giris" name="giris" type="submit" class="btn btn-primary btn-block btn-flat">Giriş Yap</button>
            </div><!-- /.col -->
          </div>
        </form>

        <div class="social-auth-links text-center">
            <a href="#" class="btn btn-block "><img src="dist/img/ostim_logo_en.png"></img> </a>
          <!--<p>- yada -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Facebook hesabı ile giriş yap</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Google+ ile giriş yap</a>-->
        </div><!-- /.social-auth-links -->

        <a href="#">Şifremi Unuttum</a><br>
        <!--<a href="register.html" class="text-center">Register a new membership</a>-->

        <a href="https://www.bahram.sanalfarbika.com/signup">Yeni Kullanıcı</a><br>
        <!--<a href="register.html" class="text-center">Register a new membership</a>-->
        
      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->