<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>

<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index.phtml" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b> <?php echo $this->translate('OSTIM') ?> </b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b> <?php echo $this->translate('OSTIM') ?> </b> <?php echo $this->translate('Virtual Enterprise') ?> </span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('New Messages') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- start message -->
                                    <!--<a href="#">
                                      <div class="pull-left">
                                        
                                          <img src="dist/img/manager-xxl.png" class="img-circle" alt="User Image"/>
                                      </div>
                                      <h4>
                                        Support Team
                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                      </h4>
                                      <p>Why not buy a new awesome theme?</p>
                                    </a>
                                  </li><!-- end message -->
                                    <!--<li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          AdminLTE Design Team
                                          <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Developers
                                          <small><i class="fa fa-clock-o"></i> Today</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Sales Department
                                          <small><i class="fa fa-clock-o"></i> Yesterday</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Reviewers
                                          <small><i class="fa fa-clock-o"></i> 2 days</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all messages') ?></a></li>
                        </ul>
                    </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Notifications') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li>
                                      <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-users text-red"></i> 5 new members joined
                                      </a>
                                    </li>
              
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-user text-red"></i> You changed your username
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all notifications') ?></a></li>
                        </ul>
                    </li>
                    <!-- Tasks: style can be found in dropdown.less -->
                    <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Works To Do') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- Task item -->
                                    <!--<a href="#">
                                      <h3>
                                        Design some buttons
                                        <small class="pull-right">20%</small>
                                      </h3>
                                      <div class="progress xs">
                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                          <span class="sr-only">20% Complete</span>
                                        </div>
                                      </div>
                                    </a>
                                  </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Create a nice theme
                                          <small class="pull-right">40%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">40% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Some task I need to do
                                          <small class="pull-right">60%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">60% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Make beautiful transitions
                                          <small class="pull-right">80%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">80% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#"><?php echo $this->translate('Show all tasks') ?></a>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->                    
                            <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                            <span class="hidden-xs"><?php /* echo $_SESSION['userName'] */ ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                              <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                                <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                <p>
                                    <?php /* echo $_SESSION['userName'] */ ?> - <?php /* echo $_SESSION['department'] */ ?>
                                    <small><!--Member since Nov. 2012--></small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Collaborating Companies') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Friends') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Followers') ?></a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">   
                                    <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('Profile') ?></a>
                                </div>
                                <div class="pull-right">
                                    <a href="<?php echo $this->url('login', array('action' => 'logout')); ?> " class="btn btn-default btn-flat"><?php echo $this->translate('Log out') ?></a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                  <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                    <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 

                </div>
                <div class="pull-left info">
                    <p><?php /* echo $_SESSION['userName']; */ ?></p>

                    <a href="#"><i class="fa fa-circle text-success"></i> <?php echo $this->translate('Active') ?></a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="<?php echo $this->translate('Search...') ?>"/>
                    <span class="input-group-btn">
                        <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->

            <ul class="sidebar-menu" id="leftside-menu">
                <li class="header"><?php echo $this->translate('Main Navigation') ?></li>
                <li class="active treeview"></li>                        
            </ul>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <?php echo $this->translate('Virtual Enterprise Control Panel') ?>
                <small></small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="https://www.bahram.sanalfabrika.com/tr/ostim/sanalfabrika/supervisor"><i class="fa fa-dashboard"></i> <?php echo $this->translate('Home') ?> </a></li>
                <!--<li class="active">Firma İşlemleri</li>-->
                <li><a href="https://www.bahram.sanalfabrika.com/tr/ostim/sanalfabrika/supervisor/coreg"><i class="fa fa-dashboard"></i> <?php echo $this->translate('Company Registration') ?> </a></li>
                <!--<li class="active">Firma İşlemleri</li>-->
            </ol>
        </section>

        <!-- Main content -->
        <!-- Main Content. Contains page content -->
        <section class="invoice">
            <!--main panel row-->
            <div class="row">
                <!--main content width, single column-->
                <div class="col-md-12">
                    <!--main panel box, with background color of #f4f4f4-->
                    <div class="box" style="background-color: #f4f4f4">
                        <!--Page main panel-->
                        <div class="box-header with-border" >
                            <h3 class="box-title"> <?php echo $this->translate('Software Information') ?> </h3>
                            <div class="box-tools pull-right" >
                                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-plus"></i></button>
                            </div>
                        </div><!--/. page main header-->                                
                        <!--main content body start-->
                        <div class="box-body">
                            <!--first collapsible panel row -->
                            <div class="row">
                                <!--first collapsible panel width, single column-->
                                <div class="col-md-12">
                                    <!--arrange first panel color to blue by assigning primary class-->
                                    <div class="box box-primary">
                                        <!--First panel Header-->
                                        <div class="box-header with-border">                                                    
                                            <h3 class="box-title"> <?php echo $this->translate('List of Companies') ?> </h3>                                                    
                                            <!--Panel 1 collapse button-->
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                            </div><!--/. button div-->
                                        </div><!--/. panel 1 header div-->
                                        <!--Panel 1 contents-->
                                        <div class="box-body">
                                            <!--Easyui grid table div start-->
                                            <div id="tt_grid_dynamic_Main">
                                                <table  id="tt_grid_dynamic" title="<?php echo $this->translate('Companies Information') ?>" ></table>
                                            </div><!--/. Easyui grid table-->
                                        </div><!-- /.box-body -->
                                    </div><!--/. primary box div-->
                                </div><!--/. first panel single column div -->
                            </div><!-- / first panel row-->

                            <!--Machine list collapsible panel row -->
                            <div class="row">
                                <!--Machine list collapsible panel width, single column-->
                                <div class="col-md-12">
                                    <!--arrange Machine list panel color to blue by assigning primary class-->
                                    <div class="box box-primary">
                                        <!--Machine list panel Header-->
                                        <div class="box-header with-border">                                                    
                                            <h3 class="box-title"> <?php echo $this->translate('List of Software') ?> </h3>                                                    
                                            <!--Machine list collapse button-->
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                            </div><!--/. button div-->
                                        </div><!--/. Machine list header div-->
                                        <!--Machine list contents-->
                                        <div class="box-body">
                                            <!--Easyui grid table div start-->
                                            <div id="tt_grid_dynamic_Main">
                                                <table  id="tt_grid_dynamic" title="<?php echo $this->translate('Software Information') ?>"></table>
                                            </div><!--/. Easyui grid table-->
                                        </div><!-- /.box-body -->
                                    </div><!--/. Machine list box div-->
                                </div><!--/. Machine list panel single column div -->
                            </div><!-- / Machine list panel row-->

                            <!--First panel row-->
                            <div class="row">
                                <!--First panel single column-->
                                <div class="col-md-12">
                                    <!--arrange First panel color to green by assigning success class-->
                                    <div class="box box-success collapsed-box" id="addNewPanel">
                                        <!--First panel Header-->
                                        <div class="box-header with-border">
                                            <h3 class="box-title"> <?php echo $this->translate('New Submission') ?> </h3>
                                            <!--First panel collapse button-->
                                            <div class="box-tools pull-right">
                                                <button class="btn btn-box-tool" onclick='$.AdminLTE.boxWidgetCRUDPanelCloser.collapse($("#firmaGuncelleme"))'  data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-plus"></i></button>
                                            </div><!--/. panel collapse button div-->
                                        </div><!--/. First panel header-->
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="ibox float-e-margins">
                                                        <div class="ibox-content">
                                                            <form method="get" class="form-horizontal">                                                                
                                                                <div class="form-group"><label class="col-sm-4 control-label"> <?php echo $this->translate('Quality Control Tool Type') ?> </label>
                                                                    <div class="col-sm-8">
                                                                        <select class="form-control select2" style="width: 100%;">                                                                    
                                                                            <option value = -1><?php echo $this->translate('Select a software type') ?></option>                                                                     
                                                                            <option>Software Type 1</option>                                                                     
                                                                            <option>Software Type 2</option>                                                                      
                                                                            <option>Software Type 3</option>                                                                      
                                                                            <option>Software Type 4</option>
                                                                        </select>
                                                                    </div>
                                                                </div>

                                                                <div class="box-footer">
                                                                    <div class="col-sm-4 col-sm-offset-8">

                                                                    </div>
                                                                </div>

                                                                <div class="box-footer">
                                                                    <div class="col-sm-12">
                                                                        <button id='addressUpdateButton' class="btn btn-white" type="submit"> <?php echo $this->translate('Update software information') ?> </button>
                                                                        <button id='addNewAddressButton' class="btn btn-primary" type="submit"> <?php echo $this->translate('Add New Software') ?> </button>
                                                                    </div>
                                                                </div>                                                              
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div><!--/. box-->
                                    </div><!--/. success box div-->
                                </div><!--/. First panel single column div -->
                            </div><!-- / First panel row-->
                            <!--First collapsible panel row -->



                            <!--Second panel row-->
                            <div class="row">
                                <!--second collapsible panel width, single column-->
                                <div class="col-md-12">
                                    <!--arrange second panel color to red by assigning danger class-->
                                    <div class="box box-danger collapsed-box" id="machineUpdate">
                                        <!--second panel Header-->                                                
                                        <div class="box-header with-border">
                                            <h3 class="box-title"><?php echo $this->translate('Update Machine Tool Information') ?></h3>
                                            <!--Second panel collapse button-->                                            
                                        </div><!--/. Second panel header-->
                                        <div class="box-body">
                                            <div class="row">
                                                <div class="col-lg-12">

                                                </div>
                                            </div>
                                        </div><!--/. box-->
                                    </div><!--/. success box div-->
                                </div><!--/. First panel single column div -->
                            </div><!-- / First panel row-->
                            <!--First collapsible panel row -->
                        </div><!--/. main body-->
                    </div><!--/.box --> 
                </div><!--/. main panel single colum-->
            </div><!--/. main panel row-->
        </section><!--/.invoice -->
    </div><!-- /.content-wrapper -->
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b><?php echo $this->translate('Version') ?></b> 1.0
        </div>
        <strong><?php echo $this->translate('Copyright') ?> &copy; 2016 <a href="" onclick="event.preventDefault();"><?php echo $this->translate('OSTIM Technology A.Ş.') ?></a>.</strong> <?php echo $this->translate('All rights reserved.') ?>
    </footer>

    <!-- Control Sidebar -->      
    <aside class="control-sidebar control-sidebar-dark">                
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading"><?php echo $this->translate('Recent Activities') ?></h3>
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading"><?php echo $this->translate('Logged into the system') ?></h4>
                                <p><!--Will be 23 on April 24th--></p>
                            </div>
                        </a>
                    </li>
                    <!--<li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                          <p>New phone +1(800)555-1234</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                          <p>nora@example.com</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                          <p>Execution time 5 seconds</p>
                        </div>
                      </a>
                    </li>-->
                </ul><!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading"><?php echo $this->translate('Task Progress') ?></h3> 
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                <?php echo $this->translate('Reviewed Companies') ?>
                                <span class="label label-danger pull-right">3%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                <?php echo $this->translate('Finished Reports') ?>
                                <span class="label label-success pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                <?php echo $this->translate('Finished Eco Efficiency Reports') ?>
                                <span class="label label-waring pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <!--<li>
                      <a href='javascript::;'>               
                        <h4 class="control-sidebar-subheading">
                          Back End Framework
                          <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                          <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>                                    
                      </a>
                    </li>-->             
                </ul><!-- /.control-sidebar-menu -->         

            </div><!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab"><?php echo $this->translate('Stat Tab Contents') ?></div><!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">            
                <form method="post">
                    <h3 class="control-sidebar-heading"><?php echo $this->translate('General Settings') ?></h3>
                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Task Progress') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('Reports') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Company Editing Permission') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Chat Settings') ?></h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Show me as online') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>                
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Turn off notifications') ?>
                            <input type="checkbox" class="pull-right" />
                        </label>                
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Delete chat history') ?>
                            <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                        </label>                
                    </div><!-- /.form-group -->
                </form>
            </div><!-- /.tab-pane -->
        </div>
    </aside><!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class='control-sidebar-bg'></div>
</div><!-- ./wrapper -->

