<div class="login-box">
    <div class="login-logo">
        <a href="">
            <b>
                <?php echo $this->translate('OSTIM') ?>
                <?php echo $this->translate('Virtual Enterprise') ?> 
            </b> 

        </a>
        <div>
            <p><?php echo $this->translate('New Registration') ?></p>
        </div>
    </div><!-- /.login-logo -->
    
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('New Customer Registration') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('New Supplier Registration') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">
                <?php echo $this->translate('OSTİM Enterprise Registration') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">                
                <?php echo $this->translate('Academia') ?>
            </button>
        </div>
    </div>
    <div class="col-sm-15">
        <div class="input-group">
            <div class="input-group-addon">
                <i class="fa fa-save"></i>
            </div>
            <button type="button" class="btn btn-default btn-block">

                <?php echo $this->translate('Expert') ?>
            </button>
        </div>
    </div>
</div><!-- /.login-box -->