<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="ln" type="hidden"  value="tr"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<body class="skin-blue sidebar-mini">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="index.phtml" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b> <?php echo $this->translate('OSTIM') ?> </b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b> <?php echo $this->translate('OSTIM') ?> </b> <?php echo $this->translate('Virtual Enterprise') ?> </span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        <li class="dropdown messages-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-envelope-o"></i>
                                <span class="label label-success">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('New Messages') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer"><a href="#"><?php echo $this->translate('Show all messages') ?></a></li>
                            </ul>
                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
                        <li class="dropdown notifications-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-bell-o"></i>
                                <span class="label label-warning">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('Notifications') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer"><a href="#"><?php echo $this->translate('Show all notifications') ?></a></li>
                            </ul>
                        </li>
                        <!-- Tasks: style can be found in dropdown.less -->
                        <li class="dropdown tasks-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-flag-o"></i>
                                <span class="label label-danger">0</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="header">0 <?php echo $this->translate('Works To Do') ?></li>
                                <li>
                                    <!-- inner menu: contains the actual data -->
                                    <ul class="menu">
                                        
                                    </ul>
                                </li>
                                <li class="footer">
                                    <a href="#"><?php echo $this->translate('Show all tasks') ?></a>
                                </li>
                            </ul>
                        </li>
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                              <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->                    
                                <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                <span class="hidden-xs"><?php /* echo $_SESSION['userName'] */ ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                  <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                                    <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                    <p>
                                        <?php /* echo $_SESSION['userName'] */ ?> - <?php /* echo $_SESSION['department'] */ ?>
                                        <small><!--Member since Nov. 2012--></small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('Collaborating Companies') ?></a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('Friends') ?></a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#"><?php echo $this->translate('Followers') ?></a>
                                    </div>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">   
                                        <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('Profile') ?></a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="<?php echo $this->url('login', array('action' => 'logout')); ?> " class="btn btn-default btn-flat"><?php echo $this->translate('Log out') ?></a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <!-- Control Sidebar Toggle Button -->
                        <li>
                            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->

        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                      <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                        <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 

                    </div>
                    <div class="pull-left info">
                        <p><?php /* echo $_SESSION['userName']; */ ?></p>

                        <a href="#"><i class="fa fa-circle text-success"></i> <?php echo $this->translate('Active') ?></a>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Ara..."/>
                        <span class="input-group-btn">
                            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->

                <ul class="sidebar-menu" id="leftside-menu">
                    <li class="header"><?php echo $this->translate('Main Navigation') ?></li>
                    <li class="active treeview"></li>                        
                </ul>

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo $this->translate('Virtual Enterprise Control Panel') ?>
                    Makina Özellikleri Tanımlama İşlemleri
                    <small></small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->serverUrl('/ostim/sanalfabrika') ?>"><i class="fa fa-dashboard"></i> <?php echo $this->translate('Home') ?> </a></li>
                    <li><a href="#"><i class="fa fa-certificate"></i> Makina İşlemleri</a></li>
                    <li class="active">Makina Özellikleri Tanımlamaları</li>
                </ol>
            </section>
            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                <!--first collapsible panel row -->
                <div class="row">
                    
                    
                    
                    <!--first collapsible panel width, single column-->
                    <div class="col-lg-12">
                        <!--arrange first panel color to blue by assigning primary class-->
                        <div id="loading-image-crud" class="box box-primary"> 
                            <!--First panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Makina Özellikleri İşlemleri </h3>
                                
                                <!--Panel 1 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 1 header div-->
                            <!--Panel 1 contents-->
                            <div id='tab_image_loader' class="box box-body" style="border-top:0px;">
                                
                                
                            <div class="alert alert-info alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-info"></i> Sistemde kullanılan tüm makina özellikleri makina kategorilerine bağlı olarak sisteme eklenebilmektedir!</h4>
                                Makina özelliği ekleyebilir , silebilir, güncelleyebilir ve kopyalayabilirsiniz....
                            </div>    
                                
                                
            <!-- Custom Tabs -->
              <div class="nav-tabs-custom" >
                <ul id="mach_prop_tab_container" class="nav nav-tabs">
                  <li class="active" ><a href="#tab_mach_prop" id="tab_mach_prop_clicker" name="tab_mach_prop_clicker" data-toggle="tab">Makina Kategorisine göre makina özellikleri</a></li>
                  <!--<li><a href="#tab_mach_prop_update" id="tab_mach_prop_update_clicker" name="tab_mach_prop_update_clicker" data-toggle="tab" >Makina Özelliği Güncelle</a></li>
                  <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>-->
                </ul>
                <div class="tab-content">
                  <div class="tab-pane active" id="tab_mach_prop">  
                    
                     <form id='unitForm' method="get" class="form-horizontal">     
                    
                    <div id="roleFormBlock" class="box box-primary" style="padding-top: 20px;">                                     
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Kategori</label>
                            <div class="col-sm-10 " >
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-code-fork"></i>
                                    </div>
                                    <div class="inner test-tree" style='overflow:auto;'>    
                                        <div id="loading-image" class='scrollbar-inner'>
                                        <ul id="tt_tree_menu2" class="easyui-tree" ></ul> 
                                        </div>
                                    </div>                                                       
                                </div>
                            </div>
                        </div>
                        <div id="mach-prop-box" class="form-group box" style="border-top : 0px; box-shadow: none;">
                            <label class="col-sm-2 control-label">Seçili Makina Kategorisi Özellikleri</label>
                            <div class="col-sm-10">
                                <div class="input-group">    
                                    <div class="input-group-addon">
                                        <i class="fa fa-hand-o-right"></i>
                                    </div>
                                    <div style="margin-bottom: -10px;" class="tag-container">
                                        <ul id="test-cabin" class="tag-box"></ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                    </div> 
                </form>  
    
                  </div><!-- /.tab-pane -->
                  <!--<div class="tab-pane box" id="tab_mach_prop_update" >
 
                   
                    The European languages are members of the same family. Their separate existence is a myth.
                    For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ
                    in their grammar, their pronunciation and their most common words. Everyone realizes why a
                    new common language would be desirable: one could refuse to pay expensive translators. To
                    achieve this, it would be necessary to have uniform grammar, pronunciation and more common
                    words. If several languages coalesce, the grammar of the resulting language is more simple
                    and regular than that of the individual languages.   
                   
                  </div>--><!-- /.tab-pane -->
                  
                </div><!-- /.tab-content -->
              </div><!-- nav-tabs-custom -->
                                
                                
                                
                                
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. first panel single column div -->
                </div><!-- / first panel row-->

                

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b><?php echo $this->translate('Version') ?></b> 1.0
            </div>
            <strong><?php echo $this->translate('Copyright') ?> &copy; 2016 <a href="" onclick="event.preventDefault();"><?php echo $this->translate('OSTIM Technology A.Ş.') ?></a></strong> <?php echo $this->translate('All rights reserved.') ?>
        </footer>

        <!-- Control Sidebar -->      
        <aside class="control-sidebar control-sidebar-dark">                
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <!-- Home tab content -->
                <div class="tab-pane" id="control-sidebar-home-tab">
                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Recent Activities') ?></h3>
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>
                                <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                                <div class="menu-info">
                                    <h4 class="control-sidebar-subheading"><?php echo $this->translate('Logged into the system') ?></h4>
                                    <p><!--Will be 23 on April 24th--></p>
                                </div>
                            </a>
                        </li>
                        <!--<li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                              <p>New phone +1(800)555-1234</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                              <p>nora@example.com</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                              <p>Execution time 5 seconds</p>
                            </div>
                          </a>
                        </li>-->
                    </ul><!-- /.control-sidebar-menu -->

                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Task Progress') ?></h3> 
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('Reviewed Companies') ?>
                                    <span class="label label-danger pull-right">3%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('Finished Reports') ?>
                                    <span class="label label-success pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    <?php echo $this->translate('Finished Eco Efficiency Reports') ?>
                                    <span class="label label-waring pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <!--<li>
                          <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                              Back End Framework
                              <span class="label label-primary pull-right">68%</span>
                            </h4>
                            <div class="progress progress-xxs">
                              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                            </div>                                    
                          </a>
                        </li>-->             
                    </ul><!-- /.control-sidebar-menu -->         

                </div><!-- /.tab-pane -->
                <!-- Stats tab content -->
                <div class="tab-pane" id="control-sidebar-stats-tab"><?php echo $this->translate('Stat Tab Contents') ?></div><!-- /.tab-pane -->
                <!-- Settings tab content -->
                <div class="tab-pane" id="control-sidebar-settings-tab">            
                    <form method="post">
                        <h3 class="control-sidebar-heading"><?php echo $this->translate('General Settings') ?></h3>
                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('Task Progress') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('Reports') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('Company Editing Permission') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>
                            <p>
                                <?php echo $this->translate('') ?>
                            </p>
                        </div><!-- /.form-group -->

                        <h3 class="control-sidebar-heading"><?php echo $this->translate('Chat Settings') ?></h3>

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('Show me as online') ?>
                                <input type="checkbox" class="pull-right" checked />
                            </label>                
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('Turn off notifications') ?>
                                <input type="checkbox" class="pull-right" />
                            </label>                
                        </div><!-- /.form-group -->

                        <div class="form-group">
                            <label class="control-sidebar-subheading">
                                <?php echo $this->translate('Delete chat history') ?>
                                <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                            </label>                
                        </div><!-- /.form-group -->
                    </form>
                </div><!-- /.tab-pane -->
            </div>
        </aside><!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class='control-sidebar-bg'></div>
    </div><!-- ./wrapper -->

</body>
