<head>
    <title><?php echo $this->translate('Virtual Enterprise') ?> | <?php echo $this->translate('User Profile Comments') ?></title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?php echo $this->basePath('onyuz/standard/assets/favicon.ico') ?>">

    <!-- Web Fonts -->
    <link rel="stylesheet" href="<?php echo $this->basePath('fonts.googleapis.com/css0bd2.css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin') ?>">

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/bootstrap/css/bootstrap.min.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/style.css') ?>">

    <!-- Bootstrap 3.3.4 -->
    <link href="<?php echo $this->basePath('css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css" /> 
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/one.style.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('plugins/bootstrap-table/bootstrap-table.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('plugins/bootstrap-editable/bootstrap-editable/css/bootstrap-editable.css') ?>">

    <!-- CSS Header and Footer -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/headers/header-default.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/footers/footer-v1.css') ?>">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/animate.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/line-icons/line-icons.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/font-awesome/css/font-awesome.min.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/scrollbar/css/jquery.mCustomScrollbar.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/sky-forms-pro/skyforms/css/sky-forms.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/sky-forms-pro/skyforms/custom/custom-sky-forms.css') ?>">
    <!--[if lt IE 9]><link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/plugins/sky-forms-pro/skyforms/css/sky-forms-ie8.css') ?>"><![endif]-->

    <!-- CSS Page Style -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/pages/profile.css') ?>">
    
    <!-- CSS Theme -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/theme-colors/default.css') ?>" id="style_color">
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/theme-skins/dark.css') ?>">

    <!-- CSS Customization -->
    <link rel="stylesheet" href="<?php echo $this->basePath('onyuz/standard/assets/css/custom.css') ?>">
    
    <!-- Bahram custom css for text rotation -->
    <link rel="stylesheet" href="<?php echo $this->basePath('plugins/bahram/bahram.css') ?>">

</head>	

<body>

    <?php echo $this->content; ?>

    <?php echo $this->inlineScript() ?>

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $this->basePath('plugins/jQuery/jQuery-2.1.4.min.js') ?>"></script>


    <!-- jQuery UI 1.11.2 -->
    <!--<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>-->
    <script src="<?php echo $this->basePath('plugins/jQueryUI/jquery-ui-1.11.2.min.js') ?>" type="text/javascript"></script>
    <!--<script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/jquery/jquery.min.js') ?>"></script>-->
    <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/jquery/jquery-migrate.min.js') ?>"></script>
    <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/bootstrap/js/bootstrap.min.js') ?>"></script>


    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->



    <!-- JS Implementing Plugins -->
    <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/back-to-top.js') ?>"></script>
    <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/smoothScroll.js') ?>"></script>
    <script src="<?php echo $this->basePath('onyuz/standard/assets/plugins/sky-forms-pro/skyforms/js/jquery-ui.min.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/plugins/counter/waypoints.min.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/plugins/counter/jquery.counterup.min.js') ?>"></script> 
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/plugins/scrollbar/js/jquery.mCustomScrollbar.concat.min.js') ?>"></script>

    <!-- JS Customization -->
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/js/custom.js') ?>"></script>

    <!-- JS Page Level -->           
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/js/app.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/js/plugins/datepicker.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath('onyuz/standard/assets/js/plugins/style-switcher.js') ?>"></script>

    <!-- multulanguage js -->
    <script src="<?php echo $this->basePath('plugins/jquery-lang-js-master/js.cookie.js') ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('plugins/jquery-lang-js-master/jquery-lang.js') ?>" type="text/javascript"></script>
    <!--<script src="js/langpack/nonDynamic.js" charset="utf-8" type="text/javascript"></script>-->

    <!--loadImager js-->
    <script type="text/javascript" src="<?php echo $this->basePath('plugins/bahram/exPlugs.js') ?>"></script>

    <!-- inline js -->        
    <script src="<?php echo $this->basePath('jsinline/languageBar.js') ?>"></script>

    <script type="text/javascript">
        jQuery(document).ready(function () {
            App.init();
            App.initCounter();
            App.initScrollBar();
            Datepicker.initDatepicker();
            StyleSwitcher.initStyleSwitcher();
        });
    </script>
    <!--[if lt IE 9]>
        <script src="assets/plugins/respond.js"></script>
        <script src="assets/plugins/html5shiv.js"></script>
        <script src="assets/plugins/placeholder-IE-fixes.js"></script>    
    <![endif]-->

</body>
</html>	