<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sanal Fabrika '. $this->translate('Login'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Bootstrap 3.3.4 -->
        <link href="<?php echo $this->basePath('bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css" />
        <!--<link href="<?php echo $this->basePath('css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css" /> -->
        <!-- easyui implementation -->
        <!--<link href="plugins/jquery-easyui-1.3.3/themes/icon.css" rel="stylesheet" type="text/css" />
        <link href="plugins/jquery-easyui-1.3.3/themes/bootstrap/easyui.css" rel="stylesheet" type="text/css" />-->
        <!-- FontAwesome 4.3.0 -->
        <!--<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />-->
        <link href="<?php echo $this->basePath('plugins/font-awesome-4.4.0/css/font-awesome.min.css') ?>" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="<?php echo $this->basePath('dist/css/AdminLTE.min.css')?>" rel="stylesheet" type="text/css" />
        <!-- iCheck -->
        <link href="<?php echo $this->basePath('plugins/iCheck/square/blue.css')?>" rel="stylesheet" type="text/css" />
        

    </head>
    <body class="login-page">
       
        
            <?php echo $this->content; ?>
            

    <!-- jQuery 2.1.4 -->
    <script src="<?php echo $this->basePath('plugins/jQuery/jQuery-2.1.4.min.js')   ?>"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo $this->basePath('bootstrap/js/bootstrap.min.js') ?>" type="text/javascript"></script>
    <!--<script src="<?php echo $this->basePath('js/bootstrap.min.js') ?>" type="text/javascript"></script>    -->
         
    <script src="<?php echo $this->basePath('plugins/iCheck/icheck.min.js') ?>" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
        
   
        
    </body>
</html>
