<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="cpk" type="hidden"  value="<?php echo $this->companyPublicKey; ?>"></input>
<input id="selectedCompanyNpk" type="hidden"  value="<?php echo $this->selectedCompanyNpk; ?>"></input>
<input id="selectedCompanyShN" type="hidden"  value="<?php echo $this->selectedCompanyShN; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="index.phtml" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b><?php echo $this->translate('OSTIM') ?></b> </span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b><?php echo $this->translate('OSTIM') ?></b> <?php echo $this->translate('V.E.') ?></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">                
                <ul class="nav navbar-nav">
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-group"></i>
                            <span id="number_of_consultants_power" class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li id="number_of_consultants" class="header"></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu" id='list_consultants'>                                    
                                </ul>
                            </li>
                            <!--<li class="footer"><a href="#"><?php echo $this->translate('Show all consultants') ?></a></li>-->
                        </ul>
                    </li>
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('New Messages') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- start message -->
                                    <!--<a href="#">
                                      <div class="pull-left">
                                        
                                          <img src="dist/img/manager-xxl.png" class="img-circle" alt="User Image"/>
                                      </div>
                                      <h4>
                                        Support Team
                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                      </h4>
                                      <p>Why not buy a new awesome theme?</p>
                                    </a>
                                  </li><!-- end message -->
                                    <!--<li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          AdminLTE Design Team
                                          <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Developers
                                          <small><i class="fa fa-clock-o"></i> Today</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Sales Department
                                          <small><i class="fa fa-clock-o"></i> Yesterday</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Reviewers
                                          <small><i class="fa fa-clock-o"></i> 2 days</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all messages') ?></a></li>
                        </ul>
                    </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Notifications') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li>
                                      <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-users text-red"></i> 5 new members joined
                                      </a>
                                    </li>
              
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-user text-red"></i> You changed your username
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all notifications') ?></a></li>
                        </ul>
                    </li>
                    <!-- Tasks: style can be found in dropdown.less -->
                    <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Works To Do') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- Task item -->
                                    <!--<a href="#">
                                      <h3>
                                        Design some buttons
                                        <small class="pull-right">20%</small>
                                      </h3>
                                      <div class="progress xs">
                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                          <span class="sr-only">20% Complete</span>
                                        </div>
                                      </div>
                                    </a>
                                  </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Create a nice theme
                                          <small class="pull-right">40%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">40% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Some task I need to do
                                          <small class="pull-right">60%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">60% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Make beautiful transitions
                                          <small class="pull-right">80%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">80% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#"><?php echo $this->translate('Show all tasks') ?></a>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->                    
                            <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                            <span class="hidden-xs"><?php /* echo $_SESSION['userName'] */ ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                              <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                                <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                <p>
                                    <?php /* echo $_SESSION['userName'] */ ?> - <?php /* echo $_SESSION['department'] */ ?>
                                    <small><!--Member since Nov. 2012--></small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Collaborating Companies') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Friends') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Followers') ?></a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">   
                                    <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('Profile') ?></a>
                                </div>
                                <div class="pull-right">
                                    <a href="<?php echo $this->url('login', array('action' => 'logout')); ?> " class="btn btn-default btn-flat"><?php echo $this->translate('Log out') ?></a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li class="dropdown language-selector" id='languages'>                          
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true">
                            <!--<img src="<?php echo $this->basePath('img/flag-uk.png') ?>"-->
                            <span class="logo-mini">EN</span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li class="active">
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-uk.png') ?>"-->
                                    <span class="logo-mini">EN</span>
                                    <span>English</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-tr.png') ?>"-->
                                    <span class="logo-mini">TR</span>
                                    <span>Türkçe</span>
                                </a>
                            </li>
                            <li >
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-ru.png') ?>"-->
                                    <span class="logo-mini">RU</span>
                                    <span>Pу́сский</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-de.png') ?>"-->
                                    <span class="logo-mini">DE</span>
                                    <span>Deutsch</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-fr.png') ?>"-->
                                    <span class="logo-mini">FR</span>
                                    <span>Français</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-ar.png') ?>"-->
                                    <span class="logo-mini">AR</span>
                                    <span>العربية</span>
                                </a>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-fa.png') ?>"-->
                                    <span class="logo-mini">FA</span>
                                    <span>فارسی</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                  <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                    <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" 
                         class="user-image" alt="User Image"/> 
                </div>
                <div class="pull-left info">
                    <p><?php /* echo $_SESSION['userName']; */ ?></p>
                    <a href="#"><i class="fa fa-circle text-success"></i>
                        <?php echo $this->translate('Active') ?>
                    </a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" 
                           placeholder="<?php echo $this->translate('Search') ?>"/>
                    <span class="input-group-btn">
                        <button type='submit' name='search' id='search-btn' 
                                class="btn btn-flat" onclick="send_general_info()"><i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->

            <ul class="sidebar-menu" id="leftside-menu">
                <li class="header">
                    <?php echo $this->translate('Main Navigation') ?>
                </li>
                <li class="active treeview">

                </li>                        
            </ul>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> 
                <?php echo $this->translate('Company Profile') ?>
                <small><?php echo $this->translate('Members Settings') ?></small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-home"></i>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index')); ?>">
                        <?php echo $this->translate('Home') ?>
                    </a>
                </li>
                <li>
                    <i class="fa fa-home"></i>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'companyprofile', 'selectedCompanyShN' => $selectedCompanyShN, 'selectedCompanyNpk' => $selectedCompanyNpk));
                        ?>">
                           <?php echo $this->translate('Company Profile') ?>
                    </a>
                </li>
                <li class="active">
                    <i class="fa fa-dashboard"></i>
                    <a href="<?php echo $this->url('sanalfabrika', array('action' => 'cpmemberset'));
                           ?>">
                           <?php echo $this->translate('Members Settings') ?>
                    </a>
                </li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="box box-primary">                
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('Registered Members') ?></h3>
                    <div id='consultant_div' class="box-tools pull-right" 
                         style='margin-right:100px; font-size:12px; width: 200px' 
                         data-balloon="" email_address =""
                         data-balloon-pos="left" onclick='send_email_to_consult(this)'>
                        <a href="#">
                            <div class="pull-left">
                                <img id='cons_image_ph' style='max-height:30px;margin-right:10px' 
                                     src="" class="img-circle" alt="User Image"/>
                            </div>
                            <h8 id='cons_name_ph'>
                            </h8>
                            <br/>
                            <small></small>
                        </a>
                    </div>
                    <div class="box-tools pull-right">                        
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <!--<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>-->
                    </div>
                </div>
                <div class="box-body" style="display: block;">
                    <div class="box-body">
                        <table id="reg_members_table" title=<?php echo $this->translate('Registered Company Personnel') ?>></table>
                    </div>
                </div> 
            </div>

            <!-- hidden diploma grids placeholder -->
<!--            <div class="box box-primary" id="diploma_grid_ph" style="visibility:hidden; display:none">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('Diplomas') ?></h3>                    
                    <div class="box-body">
                        <table id="diploma_grid" title=<?php echo $this->translate('Personnel Diploma') ?>></table>
                    </div>
                </div>
            </div>-->
            <!--/ hidden diploma grids placeholder -->

            <!-- hidden langs grids placeholder -->
<!--            <div class="box box-primary" id="langs_grid_ph" style="visibility:hidden; display:none">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('Languages') ?></h3>                    
                    <div class="box-body">
                        <table id="lang_grid" title=<?php echo $this->translate('Personnel Languages') ?>></table>
                    </div>
                </div>
            </div>-->
            <!--/ hidden langs grids placeholder -->

            <!-- hidden certs grids placeholder -->
<!--            <div class="box box-primary" id="cert_grid_ph" style="visibility:hidden; display:none">
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('Certificate') ?></h3>                    
                    <div class="box-body">
                        <table id="cert_grid" title=<?php echo $this->translate('Personnel Certificate') ?>></table>
                    </div>
                </div>
            </div>-->
            <!--/ hidden certs grids placeholder -->

            <!-- company general information setting box -->
            <div class="box box-primary">                
                <div class="box-header with-border">
                    <h3 class="box-title"><?php echo $this->translate('New Personel Submission') ?></h3>

                    <div class="box-tools pull-right">                        
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <!--<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>-->
                    </div>
                </div>

                <div class="box-body" style="display: block; margin-bottom: 150px">
                    <div class="box-body">
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs">
                                <li id='gen_info_tab_btn' class="active">
                                    <a href="#gen_info_tab" data-toggle="tab" aria-expanded="true">
                                        <?php echo $this->translate('Personnel General Information') ?>
                                    </a>
                                </li>
<!--                                <li id='edu_info_tab_btn'>
                                    <li id='edu_info_tab_btn' class='disabled' >
                                    <a id='edu_tab_toggle' aria-expanded="false">
                                    <a id='edu_tab_toggle' href="#edu_info_tab" data-toggle="tab" aria-expanded="false">
                                        <?php echo $this->translate('Personnel Education Information') ?>                                    
                                    </a>
                                </li>
                                <li id='lang_info_tab_btn'>
                                    <li id='lang_info_tab_btn' class='disabled' >
                                    <a id='lang_tab_toggle'aria-expanded="false">
                                    <a id='lang_tab_toggle' href="#lang_info_tab" data-toggle="tab" aria-expanded="false">
                                        <?php echo $this->translate('Personnel Language Information') ?>                                    
                                    </a>
                                </li> 
                                <li id='cert_info_tab_btn'>
                                    <li id='cert_info_tab_btn' class='disabled' >
                                    <a id='cert_tab_toggle'aria-expanded="false">
                                    <a id='cert_tab_toggle' href="#cert_info_tab" data-toggle="tab"  aria-expanded="false">
                                        <?php echo $this->translate('Personnel Certificate Information') ?>                                    
                                    </a>
                                </li>-->
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="gen_info_tab" personnel_id=''>
                                    <div class="box-body">
                                        <form id='personel_gen_info'>
                                            <div class="col-md-3"></div>
                                            <!-- Middle Column Start -->
                                            <div class="col-lg-6">
                                                <label for="ptitle" style="margin-top: 20px"><?php echo $this->translate('Title') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[required, maxSize[30]]" 
                                                           id="ptitle" placeholder="Enter title here please">
                                                </div>
                                                <label for="ptitle_eng" style="margin-top: 20px"><?php echo $this->translate('Title (English)') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[maxSize[30]]" 
                                                           id="ptitle_eng" placeholder="Enter title in english here please">
                                                </div>
                                                <label for="pname" style="margin-top: 20px"><?php echo $this->translate('First Name') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[required, maxSize[200]]" 
                                                           id="pname" placeholder="Enter first name here please">
                                                </div>
                                                <label for="plast" style="margin-top: 20px"><?php echo $this->translate('Last Name') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[required, maxSize[200]]" 
                                                           id="plast" placeholder="Enter last name here please">
                                                </div>
                                                <label for="ppos" style="margin-top: 20px"><?php echo $this->translate('Position') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[required, maxSize[200]]" 
                                                           id="ppos" placeholder="Enter member position here please">
                                                </div>
                                                <label for="ppos_eng" style="margin-top: 20px"><?php echo $this->translate('Position (English)') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[maxSize[200]]" 
                                                           id="ppos_eng" placeholder="Enter member position in english here please">
                                                </div>
                                                <br/>
                                                <div class="form-group">                                
                                                    <label for="psex"><?php echo $this->translate('Sex') ?></label>
                                                    <div id="psex">
                                                    </div>
                                                </div>
                                                <br/>
                                            </div>
                                            <!-- Middle Column End -->
                                            <div class="col-md-3"></div>

                                            <!-- General Information Footer Start -->
                                            <div class="box-footer col-lg-12">
                                                <button type="button" class="btn btn-primary" onclick='send_personel_general_info()'>
                                                    <?php echo $this->translate('Add') ?>
                                                </button>
                                            </div>
                                            <!-- General Information Footer End -->
                                        </form>
                                    </div>
                                </div>
                                <!-- /.tab-pane -->
                                <!-- Education information is closed -->
<!--                                <div class="tab-pane" id="edu_info_tab">
                                    <div class="box-body">
                                        <div id='member_reg_grads_ph'>
                                            <table id="member_reg_grads"></table>
                                            <hr>
                                        </div>
                                        <form role="form" id='personel_edu_info'>
                                            <div class="col-md-3"></div>
                                             Middle Column Start 
                                            <div class="col-lg-6">                                                
                                                <br/>
                                                <label for="member_diploma_ph" style="margin-top: 20px"><?php echo $this->translate('Diploma') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control validate[required, maxSize[200]]" 
                                                           id="member_diploma_ph" placeholder="Enter diploma name in english here please">
                                                </div>                                                                                                                                              
                                                <br/>
                                                <div class="form-group">                                
                                                    <label for="member_university_country_ph"><?php echo $this->translate('Country of Graduation') ?></label>
                                                    <div id="member_university_country_ph">
                                                    </div>
                                                </div>                                                                                               
                                                <br/>
                                                <div class="form-group">                                
                                                    <label for="member_university_ph"><?php echo $this->translate('University or Institute') ?></label>
                                                    <div id="member_university_ph">
                                                    </div>
                                                </div>
                                                <label for="grad_date_ph" style="margin-top: 20px"><?php echo $this->translate('Graduation Date') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="date" class="form-control" id="grad_date_ph">
                                                </div>
                                                <br/>
                                            </div>
                                             Middle Column End 
                                            <div class="col-md-3"></div>

                                             Education Information Footer Start 
                                            <div class="box-footer col-lg-12"> 
                                                <button type="button" class="btn btn-default" onclick='add_new_personnel_grad()'>
                                                    <?php echo $this->translate('Add New Diploma') ?>
                                                </button>
                                                <button type="submit" class="btn btn-primary" onclick='send_personel_edu_info()'>
                                                    <?php echo $this->translate('Continue') ?>
                                                </button>
                                            </div>
                                             Education Information Footer End 
                                        </form>
                                    </div>
                                </div>-->
                                <!-- /.tab-pane -->
                                <!-- Language information is closed -->
<!--                                <div class="tab-pane" id="lang_info_tab">
                                    <div class="box-body">
                                        <div id='member_reg_lang_ph'>
                                            <table id="member_reg_langs"></table>
                                            <hr>
                                        </div>
                                        <form role="form" id='personel_lang_info'>
                                            <div class="col-md-3"></div>
                                             Middle Column Start 
                                            <div class="col-lg-6">
                                                <label for="member_language_ph" style="margin-top: 20px"><?php echo $this->translate('Language') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control" 
                                                           id="member_language_ph" placeholder="Enter member language here please">
                                                </div>
                                                <br/>
                                            </div>
                                             Middle Column End 
                                            <div class="col-md-3"></div>

                                             Language Information Footer Start 
                                            <div class="box-footer col-lg-12">
                                                <button type="button" class="btn btn-default" onclick='add_new_personnel_lang()'>
                                                    <?php echo $this->translate('Add') ?>
                                                </button>
                                                <button type="submit" class="btn btn-primary" onclick='send_personel_lang_info()'>
                                                    <?php echo $this->translate('Continue') ?>
                                                </button>
                                            </div>
                                             Language Information Footer End 
                                        </form>
                                    </div>
                                </div>-->
                                <!-- /.tab-pane -->
                                <!-- Certificate information is closed -->
<!--                                <div class="tab-pane" id="cert_info_tab">
                                    <div class="box-body"> 
                                        <div id='member_reg_certs_ph'>
                                            <table id="member_reg_certs"></table>
                                            <hr>
                                        </div>
                                        <form role="form" id='personel_cert_info'>
                                            <div class="col-md-3"></div>
                                             Middle Column Start 
                                            <div class="col-lg-6">
                                                <label for="member_certificate_ph" style="margin-top: 20px"><?php echo $this->translate('Certificate') ?></label>
                                                <div class="input-group">                                    
                                                    <div class="input-group-addon">                                        
                                                        <i class="icon-prepend fa fa-flag-o"></i>
                                                    </div>
                                                    <input type="text" class="form-control" 
                                                           id="member_certificate_ph" placeholder="Enter member certificate here please">
                                                </div>
                                                <br/>
                                            </div>
                                             Middle Column End 
                                            <div class="col-md-3"></div>

                                             Certificate Information Footer Start 
                                            <div class="box-footer col-lg-12">                                                
                                                <button type="button" class="btn btn-primary" onclick='send_personel_cert_info()'>
                                                    <?php echo $this->translate('Submit') ?>
                                                </button>
                                            </div>
                                             Certificate Information Footer End 
                                        </form>
                                    </div>
                                </div>-->
                                <!-- /.tab-pane -->
                            </div>
                            <!-- /.tab-content -->
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- end of company general information setting -->
</section><!-- /.content -->
</div><!-- /.content-wrapper -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b><?php echo $this->translate('Version') ?></b> 1.0
    </div>
    <strong><?php echo $this->translate('Copyright') ?> &copy; 2016 <a href="" onclick="event.preventDefault();"><?php echo $this->translate('OSTIM Technology A.Ş.') ?></a></strong> <?php echo $this->translate('All rights reserved.') ?>
</footer>

<!-- Control Sidebar -->      
<aside class="control-sidebar control-sidebar-dark">                
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-theme-demo-options-tab" data-toggle="tab"><i class="fa fa-wrench"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <div>
                <h3 class="control-sidebar-heading"><?php echo $this->translate('Recent Activities') ?></h3>
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading"><?php echo $this->translate('Logged in') ?></h4>
                                <p><!--Will be 23 on April 24th--></p>
                            </div>
                        </a>
                    </li>
                    <!--<li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                          <p>New phone +1(800)555-1234</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                          <p>nora@example.com</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                          <p>Execution time 5 seconds</p>
                        </div>
                      </a>
                    </li>-->
                </ul><!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading"><?php echo $this->translate('Tasks Progress') ?></h3> 
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Ziyaret Edilen Firmalar
                                <span class="label label-danger pull-right">3%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Tamamlanan Temiz Üretim Raporları
                                <span class="label label-success pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Tamamlanan Enerji Verimliliği Raporları
                                <span class="label label-waring pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <!--<li>
                      <a href='javascript::;'>               
                        <h4 class="control-sidebar-subheading">
                          Back End Framework
                          <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                          <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>                                    
                      </a>
                    </li>-->             
                </ul><!-- /.control-sidebar-menu -->         
            </div>
        </div><!-- /.tab-pane -->
        <!-- Stats tab content -->

        <div class="tab-pane active" id="control-sidebar-theme-demo-options-tab"><?php echo $this->translate('Stat Tab Content Options') ?>
            <!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->

            <h4 class="control-sidebar-heading"><?php echo $this->translate('Layout Options') ?></h4>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="fixed" class="pull-right"><?php echo $this->translate('Fixed layout') ?></label>
                <p><?php echo $this->translate("Activate the fixed layout. You can't use fixed and boxed layouts together") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="layout-boxed" class="pull-right"><?php echo $this->translate('Boxed Layout') ?></label>
                <p><?php echo $this->translate('Activate the boxed layout') ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="sidebar-collapse" class="pull-right"><?php echo $this->translate('Toggle Sidebar') ?></label>
                <p><?php echo $this->translate("Toggle the left sidebar's state (open or collapse)") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-enable="expandOnHover" class="pull-right"><?php echo $this->translate('Sidebar Expand on Hover') ?></label>
                <p><?php echo $this->translate("Let the sidebar mini expand on hover") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-controlsidebar="control-sidebar-open" class="pull-right"><?php echo $this->translate('Toggle Right Sidebar Slide') ?></label>
                <p><?php echo $this->translate("Toggle between slide over content and push content effects") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-sidebarskin="toggle" class="pull-right"><?php echo $this->translate("Toggle Right Sidebar Skin") ?></label>
                <p><?php echo $this->translate("Toggle between dark and light skins for the right sidebar") ?></p>
            </div>

            <h4 class="control-sidebar-heading"><?php echo $this->translate("Skins") ?></h4>

            <ul class="list-unstyled clearfix">
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-blue" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div><span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;">

                            </span>
                            <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Blue") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-black" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                            <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Black") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-purple" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                            <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Purple") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-green" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                            <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Green") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-red" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                            <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Red") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-yellow" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                            <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Yellow") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-blue-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;"></span>
                            <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Blue Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-black-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                            <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                        </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Black Light") ?>/p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-purple-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                            <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Purple Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-green-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                            <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Green Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-red-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                            <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Red Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-yellow-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                            <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px;"><?php echo $this->translate("Yellow Light") ?></p>
                </li>
            </ul>

        </div><!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->

        <!--<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">            
            <form method="post">
                <h3 class="control-sidebar-heading"><?php echo $this->translate('General Settings') ?></h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Report panel usage') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Some information about this general settings option') ?>
                    </p>
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Allow mail redirect') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Other sets of options are available') ?>
                    </p>
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Other sets of options are available') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Expose author name in posts') ?>
                    </p>
                </div><!-- /.form-group -->

                <h3 class="control-sidebar-heading"><?php echo $this->translate('Chat Settings') ?></h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Show me as online') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>                
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Turn off notifications') ?>
                        <input type="checkbox" class="pull-right" />
                    </label>                
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Delete chat history') ?>
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>                
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.tab-pane -->
    </div>
</aside>
<!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>
</div><!-- ./wrapper -->

