<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="cpk" type="hidden"  value="<?php echo $this->companyPublicKey; ?>"></input>
<input id="selectedCompanyNpk" type="hidden"  value="<?php echo $this->selectedCompanyNpk; ?>"></input>
<input id="selectedCompanyShN" type="hidden"  value="<?php echo $this->selectedCompanyShN; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="index.phtml" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b><?php echo $this->translate('OSTIM') ?></b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b><?php echo $this->translate('OSTIM') ?></b><?php echo $this->translate('V.E.') ?></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">                
                <ul class="nav navbar-nav">
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-group"></i>
                            <span id="number_of_consultants_power" class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li id="number_of_consultants" class="header"></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu" id='list_consultants'>                                    
                                </ul>
                            </li>
                            <!--<li class="footer"><a href="#"><?php echo $this->translate('Show all consultants') ?></a></li>-->
                        </ul>
                    </li>
                    <!-- Messages: style can be found in dropdown.less-->
                    <li class="dropdown messages-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('New Messages') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- start message -->
                                    <!--<a href="#">
                                      <div class="pull-left">
                                        
                                          <img src="dist/img/manager-xxl.png" class="img-circle" alt="User Image"/>
                                      </div>
                                      <h4>
                                        Support Team
                                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                      </h4>
                                      <p>Why not buy a new awesome theme?</p>
                                    </a>
                                  </li><!-- end message -->
                                    <!--<li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          AdminLTE Design Team
                                          <small><i class="fa fa-clock-o"></i> 2 hours</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Developers
                                          <small><i class="fa fa-clock-o"></i> Today</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Sales Department
                                          <small><i class="fa fa-clock-o"></i> Yesterday</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <div class="pull-left">
                                          <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                                        </div>
                                        <h4>
                                          Reviewers
                                          <small><i class="fa fa-clock-o"></i> 2 days</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all messages') ?></a></li>
                        </ul>
                    </li>
                    <!-- Notifications: style can be found in dropdown.less -->
                    <li class="dropdown notifications-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Notifications') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li>
                                      <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-users text-red"></i> 5 new members joined
                                      </a>
                                    </li>
              
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                      </a>
                                    </li>
                                    <li>
                                      <a href="#">
                                        <i class="fa fa-user text-red"></i> You changed your username
                                      </a>
                                    </li>-->
                                </ul>
                            </li>
                            <li class="footer"><a href="#"><?php echo $this->translate('Show all notifications') ?></a></li>
                        </ul>
                    </li>
                    <!-- Tasks: style can be found in dropdown.less -->
                    <li class="dropdown tasks-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">0</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">0 <?php echo $this->translate('Works To Do') ?></li>
                            <li>
                                <!-- inner menu: contains the actual data -->
                                <ul class="menu">
                                    <!--<li><!-- Task item -->
                                    <!--<a href="#">
                                      <h3>
                                        Design some buttons
                                        <small class="pull-right">20%</small>
                                      </h3>
                                      <div class="progress xs">
                                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                          <span class="sr-only">20% Complete</span>
                                        </div>
                                      </div>
                                    </a>
                                  </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Create a nice theme
                                          <small class="pull-right">40%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">40% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Some task I need to do
                                          <small class="pull-right">60%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">60% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                    <!-- Task item -->
                                    <!--<li>
                                      <a href="#">
                                        <h3>
                                          Make beautiful transitions
                                          <small class="pull-right">80%</small>
                                        </h3>
                                        <div class="progress xs">
                                          <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">80% Complete</span>
                                          </div>
                                        </div>
                                      </a>
                                    </li><!-- end task item -->
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#"><?php echo $this->translate('Show all tasks') ?></a>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                          <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image"/>-->                    
                            <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                            <span class="hidden-xs"><?php /* echo $_SESSION['userName'] */ ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                              <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                                <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 
                                <p>
                                    <?php /* echo $_SESSION['userName'] */ ?> - <?php /* echo $_SESSION['department'] */ ?>
                                    <small><!--Member since Nov. 2012--></small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Collaborating Companies') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Friends') ?></a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#"><?php echo $this->translate('Followers') ?></a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">   
                                    <a href="#" class="btn btn-default btn-flat"><?php echo $this->translate('Profile') ?></a>
                                </div>
                                <div class="pull-right">
                                    <a href="<?php echo $this->url('login', array('action' => 'logout')); ?> " class="btn btn-default btn-flat"><?php echo $this->translate('Log out') ?></a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li class="dropdown language-selector" id='languages'>                          
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true">
                            <!--<img src="<?php echo $this->basePath('img/flag-uk.png') ?>"-->
                            <span class="logo-mini">EN</span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li class="active">
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-uk.png') ?>"-->
                                    <span class="logo-mini">EN</span>
                                    <span>English</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-tr.png') ?>"-->
                                    <span class="logo-mini">TR</span>
                                    <span>Türkçe</span>
                                </a>
                            </li>
                            <li >
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-ru.png') ?>"-->
                                    <span class="logo-mini">RU</span>
                                    <span>Pу́сский</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-de.png') ?>"-->
                                    <span class="logo-mini">DE</span>
                                    <span>Deutsch</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-fr.png') ?>"-->
                                    <span class="logo-mini">FR</span>
                                    <span>Français</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-ar.png') ?>"-->
                                    <span class="logo-mini">AR</span>
                                    <span>العربية</span>
                                </a>
                            <li>
                                <a href="#">
                                    <!--<img src="<?php echo $this->basePath('img/flag-fa.png') ?>"-->
                                    <span class="logo-mini">FA</span>
                                    <span>فارسی</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                  <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
                    <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" 
                         class="user-image" alt="User Image"/> 
                </div>
                <div class="pull-left info">
                    <p><?php /* echo $_SESSION['userName']; */ ?></p>
                    <a href="#"><i class="fa fa-circle text-success"></i>
                        <?php echo $this->translate('Active') ?>
                    </a>
                </div>
            </div>
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" 
                           placeholder="<?php echo $this->translate('Search') ?>"/>
                    <span class="input-group-btn">
                        <button type='submit' name='search' id='search-btn' 
                                class="btn btn-flat"><i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->

            <ul class="sidebar-menu" id="leftside-menu">
                <li class="header">
                    <?php echo $this->translate('Main Navigation') ?>
                </li>
                <li class="active treeview">

                </li>                        
            </ul>

        </section>
        <!-- /.sidebar -->
    </aside>
    <!-- Content Wrapper. Contains page content -->
    <section>
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1> 
                    <?php echo $this->translate('Company Profile') ?>
                    <small><?php echo $this->translate('Machine Park Settings') ?></small>
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'index'));
                    ?>">
                               <?php echo $this->translate('Home') ?>
                        </a>
                    </li>
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'companyprofile', 'selectedCompanyShN' => $selectedCompanyShN, 'selectedCompanyNpk' => $selectedCompanyNpk));
                               ?>">
                               <?php echo $this->translate('Company Profile') ?>
                        </a>
                    </li>
                    <li class="active">
                        <i class="fa fa-dashboard"></i>
                        <a href="<?php echo $this->url('sanalfabrika', array('action' => 'cpmp'));
                               ?>">
                               <?php echo $this->translate('Company Machine Park') ?>
                        </a>
                    </li>
                </ol>
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- company general information setting box -->
                <div class="box box-primary">                
                    <div class="box-header with-border">
                        <h3 class="box-title"><?php echo $this->translate('Profile Page Settings') ?></h3>
                        <div id='consultant_div' class="box-tools pull-right" 
                             style='margin-right:100px; font-size:12px; width: 200px' 
                             data-balloon="" email_address =""
                             data-balloon-pos="left" onclick='send_email_to_consult(this)'>
                            <a href="#">
                                <div class="pull-left">
                                    <img id='cons_image_ph' style='max-height:30px;margin-right:10px' 
                                         src="" class="img-circle" alt="User Image"/>
                                </div>
                                <h8 id='cons_name_ph'>
                                </h8>
                                <br/>
                                <small></small>
                            </a>
                        </div>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
                        </div>
                    </div>

                    <div class="box-body" style="display: block;">
                        <!-- /.box-header -->
                        <div class="box-header with-border">
                            <h3 class="box-title"><?php echo $this->translate('Machine park') ?></h3>                    
                        </div>
                        <div class="box-body">
                            <!-- Start of first column -->
                            <div class="col-lg-9">
                                <table id='mt_grid' class="easyui-datagrid" title="List of Machine Tools"></table>
                            </div>
                            <!-- End of first column -->
                            <!-- Start of second column -->
                            <div class="col-lg-3">  
                                <p>
                                    <?php echo $this->translate("Company machine park reveals your company's capabilities.") ?><br/>
                                    <?php echo $this->translate("Check machine list continuously and keep your machine park list up to date, to not to miss potential orders from customers.") ?>
                                    <button id="add_new _machine" type="button" class="btn btn-primary col-lg-12" onclick="unhide_mt_section()">
                                        <?php echo $this->translate('Add new machine') ?>
                                    </button>
                            </div>
                            <!-- End of second column -->                                        
                        </div>
                    </div>
                </div>
                <!-- start of hidden machine tool section -->   
                <div id="hidden_mt_section" style="display: none; visibility: hidden">
                    <div class="box box-danger">
                        <div class="box-header with-border">
                            <h3 class="box-title"><?php echo $this->translate('Add new machine') ?></h3>                    
                        </div>
                        <div class="box-body">
                            <form id="new_mt_form">
                                <!-- start of first new machine section -->  
                                <div class="col-lg-6">
                                    <label for="machine_categories" style="margin-top: 20px">
                                        <?php echo $this->translate('New machine tool category:') ?>
                                    </label>
                                    <div id="machine_categories"></div>

                                    <label for="machine_types" style="margin-top: 20px">
                                        <?php echo $this->translate('New machine tool type:') ?>
                                    </label>                                
                                    <div id="machine_types"></div>

                                    <label for="machine_brands" style="margin-top: 20px">
                                        <?php echo $this->translate('New machine tool brand:') ?>
                                    </label>                                
                                    <div id="machine_brands"></div>

                                    <label for="machine_series" style="margin-top: 20px">
                                        <?php echo $this->translate('New machine tool serie:') ?>
                                    </label>                                
                                    <div id="machine_series"></div>
                                </div>
                                <!-- end of first new machine section -->  
                                <!-- start of second new machine section --> 
                                <div class="col-lg-6">
                                    <label for="selected_mt_category" style="margin-top: 20px">
                                        <?php echo $this->translate('Selected Machine Category is:') ?>
                                    </label>
                                    <intput id="selected_mt_category" class="form-control" type="text" disabled="disabled" value=""></intput>
                                    <label for="selected_mt_type" style="margin-top: 20px">
                                        <?php echo $this->translate('Selected Machine Type is:') ?>
                                    </label>
                                    <intput id="selected_mt_type" class="form-control" type="text" disabled="disabled"></intput>
                                    <label for="selected_mt_brand" style="margin-top: 20px">
                                        <?php echo $this->translate('Selected Machine Brand is:') ?>
                                    </label>
                                    <intput id="selected_mt_brand" class="form-control" type="text" disabled="disabled" ></intput>
                                    <label for="selected_mt_series" style="margin-top: 20px">
                                        <?php echo $this->translate('Selected Machine Serie is:') ?>
                                    </label>
                                    <intput id="selected_mt_series" class="form-control" type="text" disabled="disabled"></intput>

                                    <button class='btn btn-primary col-md-12' id="show_sel_mt_btn" 
                                            onclick="show_sel_mt()" style="margin-top: 20px; display: none;visibility: hidden">
                                                <?php echo $this->translate('Show Machine Properties in Detail') ?>
                                    </button>
                                    <button class='btn btn-default col-md-12' id="reset_sel_mt_btn" 
                                            onclick="reset_sel_mt()" style="margin-top: 20px; display: none;visibility: hidden">
                                                <?php echo $this->translate('Reset Selections') ?>
                                    </button>
                                </div>
                                <!-- end of second new machine section --> 
                            </form>
                        </div>
                    </div>
                    <div id='sel_mt_props_div' class ='box box-success' style='display: none;visibility: hidden'>
                        <div class="box-header with-border">
                            <h3 id='sel_mt_title' class="box-title"></h3>                    
                        </div>
                        <div class='box-body'>
                            <div class='col-lg-6'>
                                <img style='width: 50%' src='<?php echo $this->translate('/onyuz/standard/assets/img/sfClients/machines/Mazak_INTEGREX-j-200-(500U).jpg') ?>' alt=''>
                                <table id="pg" style="width:100%px"></table>
                            </div>
                            <div class='col-lg-6'>
                                <form id='new_mt_details_form'>
                                    <label for="number_of_avai_mt" style="margin-top: 20px">
                                        <?php echo $this->translate('Available number of this machine tool:') ?>
                                    </label>                                
                                    <div class="input-group">
                                        <div class="input-group-addon">
                                            <i class="fa fa-info"></i>
                                        </div>
                                        <input id="number_of_avai_mt" onchange="cont_add_mt_btn()"
                                               class="form-control validate[required,custom[onlyNumberSp]]" 
                                               type="text">
                                    </div>
                                    <hr>
                                    <label for="mt_owner_cond" style="margin-top: 20px">
                                        <?php echo $this->translate('Ownership conditions:') ?>
                                    </label>
                                    <div class="form-group" id='mt_owner_cond'>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="optionsRadios_1" id="mt_owner" value="Owner" checked="">
                                                <?php echo $this->translate("Owner") ?>
                                            </label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="optionsRadios_1" id="mt_lease" value="Leasing">
                                                <?php echo $this->translate("Leasing") ?>
                                            </label>
                                        </div>
                                    </div>
                                    <hr>
                                    <label for="mt_availability" style="margin-top: 20px">
                                        <?php echo $this->translate('If machines are available for new orders:') ?>
                                    </label>                                
                                    <div class="input-group">                                    
                                        <div class="form-group" id='mt_owner_cond'>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="optionsRadios_2" id="ava_yes" value="yes" checked="">
                                                    <?php echo $this->translate("Yes") ?>
                                                </label>
                                            </div>
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="optionsRadios_2" id="ava_no" value="no">
                                                    <?php echo $this->translate("No") ?>
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <button class='btn btn-primary col-md-12' id="add_machine" onclick="add_machine()" 
                                            style="margin-top: 20px" disabled="disabled"
                                            data-balloon="Yes! Add this machine to my company machine park!" 
                                            data-balloon-pos="up">
                                                <?php echo $this->translate('Add Machine') ?>
                                    </button>                                
                                    <button class='btn btn-success col-md-12' id="prop_mt_btn" 
                                            onclick="prop_mt()" style="margin-top: 5px; display: none;visibility: hidden" 
                                            data-balloon="If your machine is not in the list. Propose it to the system!" 
                                            data-balloon-pos="up">
                                                <?php echo $this->translate("Propose New Machine") ?>
                                    </button>
                                    <button class='btn btn-default col-md-12' id="reset_all_btn" 
                                            onclick="reset_all()" style="margin-top: 5px"
                                            data-balloon="Cancel and clear all!" 
                                            data-balloon-pos="up">
                                                <?php echo $this->translate('Reset Selections') ?>
                                    </button>  
                                </form>
                            </div>
                        </div>
                    </div>                
                </div>
                <!-- end of hidden machine tool section -->
        </div>
        <!-- end of company general information setting -->
    </section> /.content 
</div><!-- /.content-wrapper -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b><?php echo $this->translate('Version') ?></b> 1.0
    </div>
    <strong><?php echo $this->translate('Copyright') ?> &copy; 2016 <a href="" onclick="event.preventDefault();"><?php echo $this->translate('OSTIM Technology A.Ş.') ?></a></strong> <?php echo $this->translate('All rights reserved.') ?>
</footer>

<!-- Control Sidebar -->      
<aside class="control-sidebar control-sidebar-dark">                
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-theme-demo-options-tab" data-toggle="tab"><i class="fa fa-wrench"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <div>
                <h3 class="control-sidebar-heading"><?php echo $this->translate('Recent Activities') ?></h3>
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading"><?php echo $this->translate('Logged in') ?></h4>
                                <p><!--Will be 23 on April 24th--></p>
                            </div>
                        </a>
                    </li>
                    <!--<li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                          <p>New phone +1(800)555-1234</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                          <p>nora@example.com</p>
                        </div>
                      </a>
                    </li>
                    <li>
                      <a href='javascript::;'>
                        <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                        <div class="menu-info">
                          <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                          <p>Execution time 5 seconds</p>
                        </div>
                      </a>
                    </li>-->
                </ul><!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading"><?php echo $this->translate('Tasks Progress') ?></h3> 
                <ul class='control-sidebar-menu'>
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Ziyaret Edilen Firmalar
                                <span class="label label-danger pull-right">3%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Tamamlanan Temiz Üretim Raporları
                                <span class="label label-success pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <li>
                        <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                                Tamamlanan Enerji Verimliliği Raporları
                                <span class="label label-waring pull-right">0%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                            </div>                                    
                        </a>
                    </li> 
                    <!--<li>
                      <a href='javascript::;'>               
                        <h4 class="control-sidebar-subheading">
                          Back End Framework
                          <span class="label label-primary pull-right">68%</span>
                        </h4>
                        <div class="progress progress-xxs">
                          <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>                                    
                      </a>
                    </li>-->             
                </ul><!-- /.control-sidebar-menu -->         
            </div>
        </div><!-- /.tab-pane -->
        <!-- Stats tab content -->

        <div class="tab-pane active" id="control-sidebar-theme-demo-options-tab"><?php echo $this->translate('Stat Tab Content Options') ?>
            <!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->

            <h4 class="control-sidebar-heading"><?php echo $this->translate('Layout Options') ?></h4>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="fixed" class="pull-right"><?php echo $this->translate('Fixed layout') ?></label>
                <p><?php echo $this->translate("Activate the fixed layout. You can't use fixed and boxed layouts together") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="layout-boxed" class="pull-right"><?php echo $this->translate('Boxed Layout') ?></label>
                <p><?php echo $this->translate('Activate the boxed layout') ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-layout="sidebar-collapse" class="pull-right"><?php echo $this->translate('Toggle Sidebar') ?></label>
                <p><?php echo $this->translate("Toggle the left sidebar's state (open or collapse)") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-enable="expandOnHover" class="pull-right"><?php echo $this->translate('Sidebar Expand on Hover') ?></label>
                <p><?php echo $this->translate("Let the sidebar mini expand on hover") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-controlsidebar="control-sidebar-open" class="pull-right"><?php echo $this->translate('Toggle Right Sidebar Slide') ?></label>
                <p><?php echo $this->translate("Toggle between slide over content and push content effects") ?></p>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <input type="checkbox" data-sidebarskin="toggle" class="pull-right"><?php echo $this->translate("Toggle Right Sidebar Skin") ?></label>
                <p><?php echo $this->translate("Toggle between dark and light skins for the right sidebar") ?></p>
            </div>

            <h4 class="control-sidebar-heading"><?php echo $this->translate("Skins") ?></h4>

            <ul class="list-unstyled clearfix">
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-blue" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div><span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;">

                            </span>
                            <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Blue") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-black" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                            <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Black") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-purple" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                            <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Purple") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-green" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                            <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Green") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-red" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                            <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Red") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-yellow" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                            <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin"><?php echo $this->translate("Yellow") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-blue-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;"></span>
                            <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Blue Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-black-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                            <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                            <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                        </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Black Light") ?>/p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-purple-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                            <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Purple Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-green-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                            <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Green Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-red-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                            <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Red Light") ?></p>
                </li>
                <li style="float:left; width: 33.33333%; padding: 5px;">
                    <a href="javascript:void(0);" data-skin="skin-yellow-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                            <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                        </div>
                        <div>
                            <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                            <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                        </div>
                    </a>
                    <p class="text-center no-margin" style="font-size: 12px;"><?php echo $this->translate("Yellow Light") ?></p>
                </li>
            </ul>

        </div><!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->


        <!--<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">            
            <form method="post">
                <h3 class="control-sidebar-heading"><?php echo $this->translate('General Settings') ?></h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Report panel usage') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Some information about this general settings option') ?>
                    </p>
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Allow mail redirect') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Other sets of options are available') ?>
                    </p>
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Other sets of options are available') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>
                    <p>
                        <?php echo $this->translate('Expose author name in posts') ?>
                    </p>
                </div><!-- /.form-group -->

                <h3 class="control-sidebar-heading"><?php echo $this->translate('Chat Settings') ?></h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Show me as online') ?>
                        <input type="checkbox" class="pull-right" checked />
                    </label>                
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Turn off notifications') ?>
                        <input type="checkbox" class="pull-right" />
                    </label>                
                </div><!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <?php echo $this->translate('Delete chat history') ?>
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>                
                </div><!-- /.form-group -->
            </form>
        </div><!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>
</div><!-- ./wrapper -->

