<!--
The #page-top ID is part of the scrolling feature.
The data-spy and data-target are part of the built-in Bootstrap scrollspy function.
-->


<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua theme-active" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="../index-2.html" class="btn-u btn-u-xs btn-u-dark btn-block">Unify Main <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="../Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="../Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->

<!--=== Header ===-->
<nav class="one-page-header navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="menu-container page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#intro">
                <span>Ostim</span> <span>S</span>anal Fabrika
                <!-- <img src="assets/img/logo1.png" alt="Logo"> -->
            </a>

            <!-- multilanguage, help ve login linkleri -->
            <!-- Topbar -->
            <div class="topbar">
                <ul class="loginbar pull-right">
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('Languages') ?>  </a>
                        <i class="fa fa-globe"></i>
                        <ul class="languages hoverSelectorBlock">
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li><a href="/ostim/sanalfabrika/login"><?php echo $this->translate('Log in') ?> </a></li>   
                </ul>
            </div>
            <!-- End Topbar -->

        </div>




        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <div class="menu-container">
                <ul class="nav navbar-nav">
                    <li class="page-scroll home">
                        <a href="#body"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('About Us') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#services"><?php echo $this->translate('Services') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#ostimServices"><?php echo $this->translate('OSTIM Services') ?></a>
                    </li>                    
<!--                    <li class="page-scroll">
                        <a href="#sfTeam"><?php echo $this->translate('VE Team') ?></a>
                    </li>-->
                    <!--                    <li class="page-scroll">
                                            <a href="#news">Haberler</a>
                                        </li>-->
                    <!--                    <li class="page-scroll">
                                            <a href="#portfolio">Portfoy</a>
                                        </li>-->
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contact Us') ?></a>
                    </li>
                    <!--                    <li class="dropdown">
                                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                                                Submenu
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li class="page-scroll"><a href="#body">Home</a></li>
                                                <li class="page-scroll"><a href="#about">About Us</a></li>
                                                <li class="page-scroll"><a href="#services">Services</a></li>
                                                <li class="page-scroll"><a href="#news">News</a></li>
                                                <li class="page-scroll"><a href="#portfolio">Portfolio</a></li>
                                                <li class="page-scroll"><a href="#contact">Contact</a></li>
                                            </ul>
                                        </li>-->
                    <!--                    <li class="page-scroll">
                                            <a href="../index-2.html">Main</a>
                                        </li>-->
                </ul>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
<!--=== End Header ===-->

<!-- Intro Section -->
<section id="intro" class="intro-section">
    <div class="fullscreenbanner-container">
        <div class="fullscreenbanner">
            <ul>
                <!-- SLIDE 1 -->
                <li data-transition="curtain-1" data-slotamount="5" data-masterspeed="700" data-title="Slide 1">
                    <!-- MAIN IMAGE -->
                    <!--<img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/sliders/revolution/bg1.jpg') ?>" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">-->
                    <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/sliders/revolution/ostimbg1.jpg') ?>" alt="slidebg1" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">

                    <!-- LAYERS -->
                    <div class="tp-caption rs-caption-1 sft start"
                         data-x="center"
                         data-hoffset="0"
                         data-y="200"
                         data-speed="800"
                         data-start="2000"
                         data-easing="Back.easeInOut"
                         data-endspeed="300">
                             <?php echo $this->translate('OSTIM') ?>  <?php echo $this->translate('Virtual Enterprise Project') ?>
                             <?php echo $this->uri ?>
                    </div>

                    <!-- LAYER -->
                    <div class="tp-caption rs-caption-2 sft"
                         data-x="center"
                         data-hoffset="0"
                         data-y="300"
                         data-speed="1000"
                         data-start="3000"
                         data-easing="Power4.easeOut"
                         data-endspeed="300"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">
                        <?php echo $this->translate('Follow Development') ?><br>
                        <?php echo $this->translate('Opening OSTIM manufacturing capabilities to the customers from all over the world') ?><!--We minimize the gap between technology and its audience.-->
                    </div>

                    <!-- LAYER -->
                    <div class="tp-caption rs-caption-3 sft"
                         data-x="center"
                         data-hoffset="0"
                         data-y="460"
                         data-speed="800"
                         data-start="3500"
                         data-easing="Power4.easeOut"
                         data-endspeed="300"
                         data-endeasing="Power1.easeIn"
                         data-captionhidden="off"
                         style="z-index: 6">
                        <span class="page-scroll"><a href="#about" class="btn-u btn-brd btn-brd-hover btn-u-light"><?php echo $this->translate('Learn more') ?></a></span>
                        <span class="page-scroll"><a href="#portfolio" class="btn-u btn-brd btn-brd-hover btn-u-light"><?php echo $this->translate('Our Job') ?>  </a></span>
                    </div>
                </li>
            </ul>
            <div class="tp-bannertimer tp-bottom"></div>
            <div class="tp-dottedoverlay twoxtwo"></div>
        </div>
    </div>
</section>
<!-- End Intro Section -->

<!--  About Section -->
<section id="about" class="about-section section-first">
    <!--<div class="block-v1">
        <div class="container">
            <div class="row content-boxes-v3">
                <div class="col-md-4 md-margin-bottom-30">
                    <i class="icon-custom rounded-x icon-bg-dark fa fa-lightbulb-o"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">Creative Desgin</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's</p>
                    </div>
                </div>
                <div class="col-md-4 md-margin-bottom-30">
                    <i class="icon-custom rounded-x icon-bg-dark fa fa-flask"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">Web Development</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <i class="icon-custom rounded-x icon-bg-dark fa fa-bolt"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm">Online Marketing</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's</p>
                    </div>
                </div>
            </div>
        </div>
    </div>-->

    <!-- Colorful Service Blocks -->
    <section class="container-fluid">
        <div class="row no-gutter equal-height-columns margin-bottom-10">
            <div class="col-sm-4">
                <div class="service-block service-block-purple no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-badge"></i>
                    <h2 class="heading-md font-light"><?php echo $this->translate('New Consortiums') ?></h2>
                    <p class="no-margin-bottom font-light"><?php echo $this->translate('You may find your appropriate partners for your project or you may contribute to the new offered projects and extend your business.') ?></p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service-block service-block-red no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-fire"></i>
                    <h2 class="heading-md font-light"><?php echo $this->translate('Automatic and Objective Negotiation Process') ?></h2>
                    <p class="no-margin-bottom font-light"><?php echo $this->translate('Multiple negotation processes has been designed and based on customer preferences different negotiation process could be selected to choose the best possible partners for customers project.') ?></p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service-block service-block-aqua no-margin-bottom content equal-height-column" style="height: 239px;">
                    <i class="icon-custom icon-md rounded icon-color-light icon-line icon-directions"></i>
                    <h2 class="heading-md font-light"><?php echo $this->translate('New Technologies Implementation') ?></h2>
                    <p class="no-margin-bottom font-light"><?php echo $this->translate('In order to improve the quality of products and guarantee the project outcomes, 3D printing and Dijital scanning technologies are provided by the OSTİM Technology A.Ş. to produce prototype products before than transition to the main manufacturing processes.') ?></p>
                </div>
            </div>
        </div>        
    </section>
    <!-- End Colorful Service Blocks -->


    <div class="about-image bg-grey">
        <div class="container">
            <div class="img-center">
                <img class="img-responsive" src="<?php echo $this->basePath('onyuz\standard\assets\img\sfClients\OSTIM_Teknoloji\Logos\OSTIM_Teknoloji_Logo_small.png') ?>" alt="">  
            </div>
            <div class="title-v1">
                <h1><?php echo $this->translate('OSTIM VIRTUAL ENTERPRISE OFFICE') ?></h1>
                <p><strong><?php echo $this->translate('OSTIM Technology A.Ş.') ?></strong> <?php echo $this->translate('supports OSTIM VE system. OSTIM VE office is placed in OSTIM Organized Industrial Zone in Ankara. The office is responsible for development and management of VE tools, programs and applications.') ?> <br>
                </p>
            </div>                
        </div>
    </div>

    <!-- ostim vision and mission-->
    <div class="container content-lg">
        <div class="title-v1">
            <h2><?php echo $this->translate('VE System Mission') ?> </h2>
            <p><strong><?php echo $this->translate('VE System Mission') ?></strong> 
                <?php echo $this->translate('is to redirect customer needs and requirements nimbly to the appropriate partners. Besides it also helps SMEs to enhance their capacity usage by discovering customer orders and get new projects.  To do so system provides following features to the customers and solution partners:') ?>
            </p>
        </div>

        <div class="row">
            <div class="col-md-6 content-boxes-v3 margin-bottom-40">
                <div class="clearfix margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-trophy"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm"><?php echo $this->translate('Profile Pages') ?></h2>
                        <p><?php echo $this->translate('OSTIM VE provides profile pages for registered users and companies to describe their capabilities in details and introduce themselves to the visiting cutomers and potential partners.') ?></p>
                    </div>
                </div>
                <div class="clearfix margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-diamond"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm"><?php echo $this->translate('Smart Macthcing') ?></h2>
                        <p><?php echo $this->translate('Provided matching algorithms check registered system data and customer requirements and propose the most appropriate available resources.') ?></p>
                    </div>
                </div>
                <div class="clearfix margin-bottom-30">
                    <i class="icon-custom icon-md rounded-x icon-bg-u icon-line icon-directions"></i>
                    <div class="content-boxes-in-v3">
                        <h2 class="heading-sm"><?php echo $this->translate('Objective Negotiation Platform') ?></h2>
                        <p><?php echo $this->translate("Different types of negotiation management processes added to VE system. According to customer preferences one of these negotiation processes are selected. The whole negotiation process is managed automatically by system without human interference. Based on incoming bids from partners and customer winner bidders are chosen and introduced by system negotiation manager.") ?></p>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/DSC_0414.jpg') ?>" alt="">
            </div>
        </div>
    </div>
    <!-- ostim vision and mission end-->

    <!-- Header integrator  -->
    <div class="parallax-quote parallaxBg">
        <div class="container">
            <div class="parallax-quote-in"> 
                <p><?php echo $this->translate('VE integrates the capabiltities of 5,200 companies in OSTIM Organized Industrial Zone with more than 20,000 machine tools and 60,000 employees under one virtual company.') ?></p>
                <small>- <?php echo $this->translate('OSTIM') ?>  -</small>
            </div>
        </div>
    </div>
    <!-- End of header integrator -->

    <!-- Testimonials -->
    <div class="what-people-say">
        <div class="container content-lg">
            <div class="title-v1">
                <h2><?php echo $this->translate('OSTIM VIRTUAL ENTERPRISE TARGETS') ?></h2>
                <p><strong><?php echo $this->translate('OSTIM Virtual Enterprise') ?> </strong> <?php echo $this->translate("aims to open OSTIM's design, engineering and manufactuirng capacity to the world by redirect customer orders instantly to the related suitable companies, enhance the collaboration between multiple SMEs and improve SME's productivity by loading their idle capacity with appropriate tasks and projects.") ?></p>
            </div>

            <!-- Testimonials Wrap -->
            <div class="testimonials-v6 testimonials-wrap">
                <div class="row margin-bottom-50">
                    <div class="col-md-6 md-margin-bottom-50">
                        <div class="testimonials-info rounded-bottom">
                            <img alt="" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/testimonials/orhanaydin.jpg') ?>" class="rounded-x">
                            <div class="testimonials-desc">
                                <p><?php echo $this->translate("OSTIM VE") ?></p>
                                <strong>Orhan AYDIN</strong>
                                <span><?php echo $this->translate('Chairman of the OSTIM Organized Industrial Zone Management Executive Board') ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="testimonials-info rounded-bottom">
                            <img alt="" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/testimonials/sedatcelikdogan.jpg') ?>" class="rounded-x">
                            <div class="testimonials-desc">
                                <p><?php echo $this->translate("OSTIM VE") ?></p>
                                <strong>Doç. Dr. Sedat ÇELİKDOĞAN</strong>
                                <span><?php echo $this->translate('Chairman of OSTIM Technology A.Ş. Executive Board') ?></span>
                            </div>
                        </div>
                    </div>
                </div><!--/end row-->

                <div class="row margin-bottom-20">
                    <div class="col-md-6 md-margin-bottom-50">
                        <div class="testimonials-info rounded-bottom">
                            <img alt="" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/testimonials/ziyaburhanettinguvenc.jpg') ?>" class="rounded-x">
                            <div class="testimonials-desc">
                                <p><?php echo $this->translate("OSTIM VE") ?></p>
                                <strong>Prof.Dr.Ziya Burhanettin Güvenç</strong>
                                <span>Ostim Teknik Üniversitesi Rektörü</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="testimonials-info rounded-bottom">
                            <img alt="" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/testimonials/ademarici.jpg') ?>" class="rounded-x">
                            <div class="testimonials-desc">
                                <p><?php echo $this->translate("OSTIM VE") ?></p>
                                <strong>Adem ARICI</strong>
                                <span><?php echo $this->translate('Manager of OSTIM Organized Industrial Zone Management') ?></span>
                            </div>
                        </div>
                    </div>
                </div><!--/end row-->
            </div>
            <!-- End Testimonials Wrap -->
        </div><!--/end container-->
    </div>
    <!-- End Testimonials -->

    <div class="parallax-counter parallaxBg" id="parallax-counter-ostim">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 col-xs-6">
                    <div class="counters">
                        <span class="counter">500000</span> <span id="counter_unit">m<sup>2</sup></span>
                        <h4 class="yellow-text"><?php echo $this->translate('Overall Manufacturing Area') ?> </h4>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="counters">
                        <span class="counter">5200</span>
                        <h4 class="yellow-text"><?php echo $this->translate('Overall Enterprise Number') ?>  </h4>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="counters">
                        <span class="counter">60000</span>
                        <h4 class="yellow-text"><?php echo $this->translate('Employees') ?>      </h4>
                    </div>
                </div>
                <div class="col-sm-3 col-xs-6">
                    <div class="counters">
                        <span class="counter">2100</span> 
                        <h4 class="yellow-text"><?php echo $this->translate('Machine Park Size') ?>    </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Services Section -->
    <section id="services">
        <div class="container content-lg">
            <div class="title-v1">
                <h2><?php echo $this->translate('VE Services') ?><!--Our Services--></h2>
                <p><?php echo $this->translate("VE system services are provided under three main categories:") ?> 
                    <strong><?php echo $this->translate('Resource Discovery') ?></strong>, 
                    <strong><?php echo $this->translate('Project Management') ?></strong> <?php echo $this->translate('and') ?> 
                    <strong><?php echo $this->translate('Resource Definition') ?></strong></p>
            </div>

            <div class="row service-box-v1">
                <div class="col-md-4 col-sm-6">
                    <div class="service-block service-block-default">
                        <i class="icon-custom icon-lg icon-bg-u rounded-x fa fa-lightbulb-o"></i>
                        <h2 class="heading-md"><?php echo $this->translate('Resource Discovery') ?></h2>
                        <p><?php echo $this->translate('You may find your required human, information and physical (machinery, raw material and etc.) here') ?></p>
                        <ul class="list-unstyled">
                            <li style="font-size: 11px">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'clientspage')); ?>">
                                    <?php echo $this->translate('VE Companies') ?>                                    
                                </a>
                            </li>
                            <li style="font-size: 11px;">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'sfmachines')); ?>">
                                    <?php echo $this->translate('VE Machine Park') ?>                                    
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('VE Raw Materials') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('VE Waste') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('VE Human Resources') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('VE Products') ?>
<!--                                    <span style="font-size: 9px" class="label label-danger pull-right">
                                    <?php echo $this->translate('Members Only') ?>
                                    </span>-->
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="service-block service-block-default">
                        <i class="icon-custom icon-lg icon-bg-u rounded-x icon-line icon-present"></i>
                        <h2 class="heading-sm"><?php echo $this->translate('Project Management') ?></h2>
                        <p><?php echo $this->translate('To manage existing projects or submit a new order you may use this section') ?></p>
                        <ul class="list-unstyled">
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Negotiation Management System') ?>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Submit new Order') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Manage Your Project') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('View Project Pool') ?>
                                    <span style="font-size: 8px" class="label label-danger pull-right">
                                        <?php echo $this->translate('Members Only') ?>
                                    </span>
                                </a>
                            </li>                        
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="service-block service-block-default">
                        <i class="icon-custom icon-lg icon-bg-u rounded-x icon-line icon-rocket"></i>
                        <h2 class="heading-sm"><?php echo $this->translate('Resource Definition') ?></h2>
                        <p><?php echo $this->translate('You may define your available different resources here') ?></p>
                        <ul class="list-unstyled">
                            <!--                            <li style="font-size: 12px">
                                                            <a href="<?php echo $this->url('sanalfabrika', array('action' => 'registration')); ?>">
                            <?php echo $this->translate('Add Company') ?>
                                                            </a>
                                                        </li>-->
                            <li style="font-size: 11px">
                                <a href="<?php echo $this->url('sanalfabrika', array('action' => 'registration')); ?>">
                                    <?php echo $this->translate('Add User') ?>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Add Machine Tool') ?>
                                </a>
                            </li>
                            <li style="font-size: 12px">
                                <a href="">
                                    <?php echo $this->translate('Add Product') ?>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Add Raw Material') ?>
                                </a>
                            </li>
                            <li style="font-size: 11px">
                                <a href="">
                                    <?php echo $this->translate('Add Waste') ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> 

        <div class="title-v1">
            <h2><?php echo $this->translate('OSTIM Technology Projects') ?></h2>
            <p><?php echo $this->translate('OSTIM Technology R&D Center, collaborates researches and projects with the aim of developing high value added, high tech products under university and industry collaboration framework.') ?></p>
        </div>

        <ul class="list-unstyled row portfolio-box-v1">
            <li class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/tren.jpg') ?>" alt="">
                <div class="portfolio-box-v1-in">
                    <h3><?php echo $this->translate('Indigenous Wind Turbine Project') ?></h3>
                    <p><?php echo $this->translate('Renewable Energy Cluster Project') ?></p>
                    <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" target="_blank" href="http://www.ostimteknoloji.com/"><?php echo $this->translate('Read More') ?></a>
                </div>
            </li>
            <li class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/tank.png') ?>" alt="">
                <div class="portfolio-box-v1-in">
                    <h3><?php echo $this->translate('Indigenous Main Battle Tank Motor Project: TM-1150') ?></h3>
                    <p><?php echo $this->translate('Defense Cluster Project') ?></p>
                    <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" target="_blank" href="http://www.ostimteknoloji.com/"><?php echo $this->translate('Read More') ?></a>
                </div>
            </li>
            <li class="col-sm-4">
                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/turbine.jpg') ?>" alt="">
                <div class="portfolio-box-v1-in">
                    <h3><?php echo $this->translate('Indigenous Subway Train Project') ?></h3>
                    <p><?php echo $this->translate('Railed Systems Cluster Project') ?></p>
                    <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" target="_blank" href="http://www.ostimteknoloji.com/"><?php echo $this->translate('Read More') ?></a>
                </div>
            </li>
        </ul>
    </section>
    <!-- End Services Section -->

    <!--OSTIM Services Section -->
    <section id="ostimServices">
        <div class="container content-lg">
            <div class="title-v1">
                <h2><?php echo $this->translate('OSTIM Services') ?></h2>
                <p><?php echo $this->translate('OSTIM Organized Industrial Zone management provides various servises.') ?> <br>
                    <?php echo $this->translate('Some of these services are mentioned below') ?></p>
            </div>


            <div class="row">
                <div class="col-md-4 content-boxes-v6 md-margin-bottom-50">
                    <i class="rounded-x   glyph-icon  flaticon-house157"></i>
                    <h1 class="title-v3-md text-uppercase margin-bottom-10"><?php echo $this->translate('Infrastrcuture Services') ?></h1>
                    <p><?php echo $this->translate('') ?></p>

                    <div class="test">
                        <!--<div class=" col-md-4 col-sm-6 glyph-icon flaticon-battery151"></div>-->
                        <div class="service-block service-block-default">
                            <ul class="list-unstyled text-left no-padding" >     
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-transmission-tower margin-right-10"></i><a  href="http://ostim.com.tr/List/ListItem/4250?lid=413" class="js-newTab" data-popup="width=200,height=200"  ><?php echo $this->translate('Electric Management and Maitenance') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-rubbish3 margin-right-10"></i><a  href="http://ostim.com.tr/List/ListItem/4253?lid=413" class="js-newTab" data-popup="width=200,height=200"  ><?php echo $this->translate('Environemnt and Security') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-pipe5 margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/322097?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Gas Management and Maintenance') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-crane19 margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4255?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate("Office and Work Permit") ?></a></li>  
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-truck63 margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4251?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Town Planning and Infrastructure') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  fa fa-database margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4258?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('IT and Computing Center') ?></a></li>
                            </ul>  
                        </div>  
                    </div>

                </div>
                <div class="col-md-4 content-boxes-v6 md-margin-bottom-50">
                    <i class="rounded-x  fa fa-users"></i>
                    <h2 class="title-v3-md text-uppercase margin-bottom-10"><?php echo $this->translate('Customer Services') ?> / <?php echo $this->translate('Financial Services') ?></h2>
                    <p><?php echo $this->translate('') ?></p>

                    <div class="test">   
                        <div class="service-block service-block-default">           
                            <ul class="list-unstyled text-left no-padding" >     
                                <li><i class=" icon-lg  rounded-x  fa fa-comments-o  margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4257?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Customer Relationship') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  icon-line glyph-icon  flaticon-helmet6 margin-right-10"></i><a href='http://www.ostimistihdam.com/tr/default' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('OSTIM Employment Office') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  fa fa-briefcase margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4252?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Fair and Organizations') ?></a></li>
                                <li><i class=" icon-lg  rounded-x fa fa-bar-chart-o margin-right-10"></i><a href='http://ostim.com.tr/List/ListItem/4261?lid=413' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Financial and Administrative Affairs') ?></a></li>  
                            </ul> 
                        </div>
                    </div>

                </div>
                <div class="col-md-4 content-boxes-v6">
                    <i class="rounded-x  icon-camera"></i>
                    <h2 class="title-v3-md text-uppercase margin-bottom-10"><?php echo $this->translate('Press and Public Relations') ?></h2>
                    <p><?php echo $this->translate('') ?></p>

                    <div class="test">
                        <div class="service-block service-block-default">
                            <ul class="list-unstyled text-left no-padding" >     
                                <li><i class=" icon-lg  rounded-x  fa fa-camera  margin-right-10"></i><a href='http://ostim.com.tr/WebContent/WebContent/3309' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Organizational Photo Gallery') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  fa fa-edit margin-right-10"></i><a href='http://ostim.com.tr/WebContent/WebContent/3316' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Papers and Journals') ?></a></li>
                                <li><i class=" icon-lg  rounded-x  fa fa-video-camera margin-right-10"></i><a href='http://ostim.com.tr/WebContent/WebContent/3311' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Videos') ?></a></li>
                                <li><i class=" icon-lg  rounded-x fa fa-file-archive-o margin-right-10"></i><a href='http://ostim.com.tr/WebContent/WebContent/3321' class="js-newTab" data-popup="width=200,height=200"><?php echo $this->translate('Documents') ?></a></li>  
                            </ul>
                        </div>
                    </div>
                </div>
            </div> 
        </div>

        <!--        <ul class="list-unstyled row portfolio-box-v1">
                    <li class="col-sm-4">
                        <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/mockup/img1.jpg') ?>" alt="">
                        <div class="portfolio-box-v1-in">
                            <h3>Collective Package</h3>
                            <p>Web Design, Mock-up</p>
                            <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" href="#">Read More</a>
                        </div>
                    </li>
                    <li class="col-sm-4">
                        <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/mockup/img2.jpg') ?>" alt="">
                        <div class="portfolio-box-v1-in">
                            <h3>Ahola Company</h3>
                            <p>Brand Design, UI</p>
                            <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" href="#">Read More</a>
                        </div>
                    </li>
                    <li class="col-sm-4">
                        <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/mockup/img4.jpg') ?>" alt="">
                        <div class="portfolio-box-v1-in">
                            <h3>Allan Project</h3>
                            <p>Web Development, HTML5</p>
                            <a class="btn-u btn-u-sm btn-brd btn-brd-hover btn-u-light" href="#">Read More</a>
                        </div>
                    </li>
                </ul>        -->
    </section>
    <!-- End OSTIM Services Section -->

    <!-- header integrator  -->
    <!--    <div class="parallax-quote parallaxBg">
            <div class="container">
                <div class="parallax-quote-in"> 
                    <p><?php echo $this->translate('Integrating the Capabilities and Capacities of more than 5,000 Companies with 60,000 Employees') ?>50 bin çalışanı ve 20 bin tezgahı <span class="color-green">olan bir fabrikanın</span> kabiliyetlerini. <br> Tek bir havuzda topladık.</p>
                    <small>- <?php echo $this->translate('OSTIM') ?>  -</small>
                </div>
            </div>
        </div>-->
    <!-- header integrator  end-->

    <!-- our team  -->
<!--    <section id='sfTeam'>
    <div class="team-v1 bg-grey content-lg">
            <div class="container">
                <div class="title-v1">
                    <h2><?php echo $this->translate('VE Team') ?>     </h2>
                    <p>Academic researches and platform development studies started on 2012 in Middle East Technical University. Research phase finalized on 2015 and dissemination phase started afterward. VE platform for business use in OSTIM organized zone started since 2015 by <strong>OSTIM Virtual Enterprise Team</strong>. </p>
                </div>
    
                <ul class="list-unstyled row">
                    <li class="col-sm-3 col-xs-6 md-margin-bottom-30">
                        <div class="team-img">
                            <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/Team/bahram.jpg') ?>" alt="">
                            <ul>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <h3>Bahram Lotfi Sadigh</h3>
                        <h4>/ <?php echo $this->translate('Mechanical Engineer')?></h4>
                        <p><?php echo $this->translate('Finished his PhD research on virtual enterprise issue and started to coordinate activities to develop VE commercial software.')?></p>
                    </li>
                    <li class="col-sm-3 col-xs-6 md-margin-bottom-30">
                        <div class="team-img">
                            <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/Team/zeynel.jpg') ?>" alt="">
                            <ul>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <h3>Mustafa Zeynel Dağlı</h3>
                        <h4>/ <?php echo $this->translate('Code Developer')?></h4>
                        <p><?php echo $this->translate('Code developer')?></p>
                    </li>                    
                    <li class="col-sm-3 col-xs-6 md-margin-bottom-30">
                        <div class="team-img">
                            <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/Team/okan.jpg') ?>" alt="">
                            <ul>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <h3>Okan Ciran</h3>
                        <h4>/ <?php echo $this->translate('Database Specialist')?></h4>
                        <p><?php echo $this->translate('Database Specialist')?></p>
                    </li>                    
                    <li class="col-sm-3 col-xs-6 md-margin-bottom-30">
                        <div class="team-img">
                            <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/sfSystem/Team/durali.jpg') ?>" alt="">
                            <ul>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-custom icon-sm rounded-x fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                        <h3>Durali Çiçek</h3>
                        <h4>/ <?php echo $this->translate('Software Enginner')?></h4>
                        <p><?php echo $this->translate('Social Media Specialist')?></p>
                    </li>
                </ul>
            </div>
        </div>
    </section>-->
    <!-- our team  end-->

</section>
<!--  About Section -->



<!-- News Section -->
<!--<section id="news" class="news-section">
    <div class="container content-lg">
        <div class="title-v1">
            <h2><?php echo $this->translate('Latest News') ?>Latest News</h2>
            <p>We do <strong>things</strong> differently company providing key digital services. <br>
                Focused on helping our clients to build a <strong>successful</strong> business on web and mobile.</p>
        </div>

        <div class="row news-v1">
            <div class="col-md-4 md-margin-bottom-40">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/img1.jpg') ?>" alt="">
                    <h3><a href="#">Focused on helping our clients to build a successful business</a></h3>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
                    <ul class="list-inline news-v1-info">
                        <li><span>By</span> <a href="#">Kathy Reyes</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> July 02, 2014</li>
                        <li class="pull-right"><a href="#"><i class="fa fa-comments-o"></i> 14</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4 md-margin-bottom-40">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/img4.jpg') ?>" alt="">
                    <h3><a href="#">We build your website to realise your vision and best product</a></h3>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
                    <ul class="list-inline news-v1-info">
                        <li><span>By</span> <a href="#">John Clarck</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> July 02, 2014</li>
                        <li class="pull-right"><a href="#"><i class="fa fa-comments-o"></i> 07</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4">
                <div class="news-v1-in">
                    <img class="img-responsive" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/contents/img3.jpg') ?>" alt="">
                    <h3><a href="#">Focused on helping our clients to build a successful business</a></h3>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores.</p>
                    <ul class="list-inline news-v1-info">
                        <li><span>By</span> <a href="#">Tina Kruiger</a></li>
                        <li>|</li>
                        <li><i class="fa fa-clock-o"></i> July 02, 2014</li>
                        <li class="pull-right"><a href="#"><i class="fa fa-comments-o"></i> 22</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="parallax-twitter parallaxBg">
        <div class="container parallax-twitter-in">
            <div class="margin-bottom-30">
                <i class="icon-custom rounded-x icon-bg-blue fa fa-twitter"></i>
            </div>

            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <ul class="list-unstyled owl-twitter-v1">
                        <li class="item">
                            <p>Unify has reached 10000 plus sales and we just want to thank you to our all customers for being part of the Unify Template success <a href="http://bit.ly/1c0UN3Y">http://bit.ly/1c0UN3Y</a><p>
                                <span>3 min ago via <a href="https://twitter.com/htmlstream">@htmlstream</a></span>
                        </li>
                        <li class="item">
                            <p><a href="#">@htmlstream</a> jQuery lightGallery - Lightweight jQuery lightbox gallery for displaying image and video gallery <a href="#">http://sachinchoolur.github.io/lightGallery</a> <a href="#">#javascript</a></p>
                            <span>10 min ago Retweeted by <a href="https://twitter.com/htmlstream">@twbootstrap</a></span>
                        </li>
                        <li class="item">
                            <p>New 100% Free Stock Photos. Every. Single. Day. Everything you need for your creative projects. <a href="#">http://publicdomainarchive.com</a></p>
                            <span>30 min ago via <a href="https://twitter.com/htmlstream">@wrapbootstrap</a></span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>-->
<!-- End News Section -->

<!-- Portfolio Section -->
<!--<section id="portfolio" class="about-section">
    <div class="container content-lg">
        <div class="title-v1">
            <h2><?php echo $this->translate('Our Portfolio') ?>Our Portfolio</h2>
            <p>We do <strong>things</strong> differently company providing key digital services. <br>
                Focused on helping our clients to build a <strong>successful</strong> business on web and mobile.</p>
        </div>


        <div class="cube-portfolio">
            <div id="filters-container" class="cbp-l-filters-button">
                <div data-filter="*" class="cbp-filter-item-active cbp-filter-item"> All </div>
                <div data-filter=".print" class="cbp-filter-item"> Print </div>
                <div data-filter=".web-design" class="cbp-filter-item"> Web Design </div>
                <div data-filter=".motion" class="cbp-filter-item"> Motion </div>
            </div>/end Filters Container

            <div id="grid-container" class="cbp-l-grid-gallery">
                <div class="cbp-item print motion">
                    <a href="assets/ajax/project1.html" class="cbp-caption cbp-singlePageInline"
                       data-title="World Clock Widget<br>by Paul Flavius Nechita">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/1.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">World Clock Widget</div>
                                    <div class="cbp-l-caption-desc">by Paul Flavius Nechita</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item web-design">
                    <a href="assets/ajax/project2.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Bolt UI<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/2.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Bolt UI</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item print motion">
                    <a href="assets/ajax/project3.html" class="cbp-caption cbp-singlePageInline"
                       data-title="WhereTO App<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/3.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">WhereTO App</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item web-design print">
                    <a href="assets/ajax/project4.html" class="cbp-caption cbp-singlePageInline"
                       data-title="iDevices<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/11.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">iDevices</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item motion">
                    <a href="assets/ajax/project5.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Seemple* Music for iPad<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/5.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Seemple* Music for iPad</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item print motion">
                    <a href="assets/ajax/project6.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Remind~Me Widget<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/6.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Remind~Me Widget</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item web-design print">
                    <a href="assets/ajax/project7.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Workout Buddy<br>by Tiberiu Neamu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/7.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Workout Buddy</div>
                                    <div class="cbp-l-caption-desc">by Tiberiu Neamu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item print">
                    <a href="assets/ajax/project8.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Digital Menu<br>by Cosmin Capitanu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/8.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Digital Menu</div>
                                    <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="cbp-item motion">
                    <a href="assets/ajax/project9.html" class="cbp-caption cbp-singlePageInline"
                       data-title="Holiday Selector<br>by Cosmin Capitanu">
                        <div class="cbp-caption-defaultWrap">
                            <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/portfolio/4.jpg') ?>" alt="">
                        </div>
                        <div class="cbp-caption-activeWrap">
                            <div class="cbp-l-caption-alignLeft">
                                <div class="cbp-l-caption-body">
                                    <div class="cbp-l-caption-title">Holiday Selector</div>
                                    <div class="cbp-l-caption-desc">by Cosmin Capitanu</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>

            <div class="cbp-l-loadMore-button">
                <a href="assets/ajax/loadMore.html" class="cbp-l-loadMore-button-link">LOAD MORE</a>
            </div>
        </div>
    </div>

     ostim clients 
    <div class="clients-section parallaxBg">
        <div class="container">
            <div class="title-v1">
                <h2><?php echo $this->translate('Our Clients') ?>Our Clients</h2>
            </div>
            <ul class="owl-clients-v2">
                <li class="item"><a href="http://www.ostimsavunma.org/" class="js-newTabClients" data-popup="width=200,height=200"  ><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/ossa.png') ?>" alt=""></a></li>
                <li class="item"><a href="https://www.tai.com.tr" class="js-newTabClients" data-popup="width=200,height=200"><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/tai.png') ?>" alt=""></a></li>
                <li class="item"><a href="http://www.havelsan.com.tr/" class="js-newTabClients" data-popup="width=200,height=200"><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/havelsan.jpg') ?>" alt=""></a></li>
                <li class="item"><a href="http://www.anadoluraylisistemler.org/tr/content/k%C3%BCme-hakk%C4%B1nda/24" class="js-newTabClients" data-popup="width=200,height=200"><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/arus.png') ?>" alt=""></a></li>
                <li class="item"><a href="http://www.roketsan.com.tr/" class="js-newTabClients" data-popup="width=200,height=200"><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/roketsan.jpg') ?>" alt=""></a></li>
                <li class="item"><a href="http://www.tei.com.tr/" class="js-newTabClients" data-popup="width=200,height=200"><img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/clients/tei.png') ?>" alt=""></a></li>
            </ul>
        </div>
    </div>
     ostim clients end 

     testemonial slider one person 
    <div class="testimonials-v3">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <ul class="list-unstyled owl-ts-v1">
                        <li class="item">
                            <img class="rounded-x img-bordered" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/team/kayhanolanca.jpg') ?>" alt="">
                            <div class="testimonials-v3-title">
                                <p>Dr.Kayhan Olanca</p>
                                <span>Ostim Organize Sanayi Bölge Müdürlüğü Koordinatör</span>
                            </div>
                            <p>I just wanted to tell you how much I like to use Unify - <strong>it's so sleek and elegant!</strong> <br>
                                The customisation options you implemented are countless, and I feel sorry I can't use them all. Good job, and keep going!<p>
                        </li>
                        <li class="item">
                            <img class="rounded-x img-bordered" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/team/gulnazkaraosmanoglu.jpg') ?>" alt="">
                            <div class="testimonials-v3-title">
                                <p>Gülnaz Karaosmanoğlu</p>
                                <span>Ostim Vakfı, Genel Sekreter</span>
                            </div>
                            <p>Keep up the great work. Your template is by far the best on the market in terms of features, quality and value or money.</p>
                        </li>
                        <li class="item">
                            <img class="rounded-x img-bordered" src="<?php echo $this->basePath('onyuz/One-Page/assets/img/team/borayasa.jpg') ?>" alt="">
                            <div class="testimonials-v3-title">
                                <p>Bora Yaşa</p>
                                <span>OSTİM Medical Küme Koordinatörü </span>
                            </div>
                            <p>So far I really like the theme. I am looking forward to exploring more of your themes. Thank you!</p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
     testemonial slider one person end

</section>-->
<!-- End Portfolio Section -->

<!-- Contact Section -->
<section id="contact" class="contacts-section">
    <div class="container content-lg">
        <div class="title-v1">
            <h2><?php echo $this->translate('Contact us') ?><!--Contact Us--></h2>
            <p><?php echo $this->translate('') ?></p>
        </div>

        <div class="row contacts-in">
            <div class="col-md-6 md-margin-bottom-40">
                <ul class="list-unstyled">
                    <li><i class="fa fa-home"></i> Ostim Organize Sanayi Bölge Müdürlüğü 
                        100. Yıl Bulvarı No: 101/A, 06370, Ostim / Ankara-TÜRKİYE</li>
                    <li><i class="fa fa-phone"></i> +90 312 385 50 90 </li>
                    <li><i class="fa fa-fax"></i> +90 312 354 58 98</li>  
                    <li><i class="fa fa-envelope"></i> <a href="info_example.html">sanalfabrika@ostim.com.tr</a></li>
                    <li><i class="fa fa-globe"></i> <a href="http://htmlstream.com/">www.ostim.com.tr</a></li>
                </ul>
            </div>

            <div class="col-md-6">
                <form action="http://htmlstream.com/preview/unify-v1.8/One-Page/assets/php/sky-forms-pro/demo-contacts-process.php" method="post" id="sky-form3" class="sky-form contact-style">
                    <fieldset>
                        <label><?php echo $this->translate('Name') ?><!--Name--></label>
                        <div class="row">
                            <div class="col-md-7 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <input type="text" name="name" id="name" class="form-control">
                                </div>
                            </div>
                        </div>

                        <label><?php echo $this->translate('Email') ?> <!--Email--> <span class="color-red">*</span></label>
                        <div class="row">
                            <div class="col-md-7 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <input type="text" name="email" id="email" class="form-control">
                                </div>
                            </div>
                        </div>

                        <label>Message</label>
                        <div class="row">
                            <div class="col-md-11 margin-bottom-20 col-md-offset-0">
                                <div>
                                    <textarea rows="8" name="message" id="message" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>

                        <p><button type="submit" class="btn-u btn-brd btn-brd-hover btn-u-dark"><?php echo $this->translate('Send Message') ?><!--Send Message--></button></p>
                    </fieldset>

                    <div class="message">
                        <i class="rounded-x fa fa-check"></i>
                        <p>Your message was successfully sent!</p>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="copyright-section">
        <p><?php echo $this->translate('Copyright') ?> &copy; OSTİM Teknoloji 2016<!--2015 &copy; All Rights Reserved. Unify Theme by--> <a target="_blank" href="https://twitter.com/ostimosb"><?php echo $this->translate('OSTIM') ?></a></p>
        <ul class="social-icons">
            <li><a href="https://www.facebook.com/OstimOSB/" data-original-title="Facebook" class="social_facebook rounded-x js-sociaLinks js-sociaLinks"></a></li>
            <li><a href="https://twitter.com/ostimosb" data-original-title="Twitter" class="social_twitter rounded-x js-sociaLinks"></a></li>
            <li><a href="https://plus.google.com/+OST%C4%B0MOSB1967" data-original-title="Goole Plus" class="social_googleplus rounded-x js-sociaLinks"></a></li>
            <li><a href="https://www.instagram.com/ostimosb/" data-original-title="Instagram" class="social_instagram rounded-x js-sociaLinks"></a></li>
            <li><a href="https://www.linkedin.com/in/ostim-osb-2b94b847" data-original-title="Linkedin" class="social_linkedin rounded-x js-sociaLinks"></a></li>
            <!--<li><a href="https://www.instagram.com/ostimosb/" data-original-title="Instagram" class="social_instagram rounded-x"></a></li>-->

        </ul>
        <span class="page-scroll"><a href="#intro"><i class="fa fa-angle-double-up back-to-top"></i></a></span>
    </div>
</section>    
<!-- End Contact Section -->


