<!DOCTYPE html> 

<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input> 
<input id="key" type="hidden"  value="<?php echo $this->key; ?>"></input> 
<input id="pktemp" type="hidden" value=""></input>

<body>
    <!--=== Style Switcher ===-->    
    <i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
    <div class="style-switcher animated fadeInRight">
        <div class="style-swticher-header">
            <div class="style-switcher-heading"><?php echo $this->translate('Style Switcher') ?></div>            
            <div class="theme-close"><i class="icon-close"></i></div>
        </div>

        <div class="style-swticher-body">
            <!-- Theme Colors -->
            <div class="style-switcher-heading"><?php echo $this->translate('Theme Colors') ?></div>
            <ul class="list-unstyled">
                <li class="theme-default theme-active" data-style="default" data-header="light"></li>
                <li class="theme-blue" data-style="blue" data-header="light"></li>
                <li class="theme-orange" data-style="orange" data-header="light"></li>
                <li class="theme-red" data-style="red" data-header="light"></li>
                <li class="theme-light" data-style="light" data-header="light"></li>
                <li class="theme-purple last" data-style="purple" data-header="light"></li>
                <li class="theme-aqua" data-style="aqua" data-header="light"></li>
                <li class="theme-brown" data-style="brown" data-header="light"></li>
                <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
                <li class="theme-light-green" data-style="light-green" data-header="light"></li>
                <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
                <li class="theme-teal last" data-style="teal" data-header="light"></li>
            </ul>

            <!-- Theme Skins -->
            <div class="style-switcher-heading"><?php echo $this->translate('Theme Skins') ?></div>
            <div class="row no-col-space margin-bottom-20 skins-section">
                <div class="col-xs-6">
                    <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
                </div>
                <div class="col-xs-6">
                    <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn"><?php echo $this->translate('Dark') ?></button>
                </div>
            </div>       

            <hr>

            <!-- Theme Type -->
            <div class="style-switcher-heading"><?php echo $this->translate('Theme Type') ?></div>
            <div class="row margin-bottom-10">
                <div class="col-xs-12">
                    <a href="index-2.html" class="btn-u btn-u-xs btn-u-dark btn-block">Main Demo Page</a>
                </div>
            </div>        
            <div class="row no-col-space">
                <div class="col-xs-6">
                    <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
                </div>
                <div class="col-xs-6">
                    <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
                </div>
            </div>            
        </div>
    </div><!--/style-switcher-->
    <!--=== End Style Switcher ===-->   

    <!--=== Content Part ===-->    
    <div class="container" >
        <!--Reg Block-->
        <div class="reg-block " >
            <form method="post" id="userConformationForm">
                <div class='box' id='form-loading-image'>
                    <div class="reg-block-header"  >
                        <h2><?php echo $this->translate('Confirm Registration') ?></h2>
                        <!--<ul class="social-icons text-center">
                            <li><a class="rounded-x social_facebook" data-original-title="Facebook" href="#"></a></li>
                            <li><a class="rounded-x social_twitter" data-original-title="Twitter" href="#"></a></li>
                            <li><a class="rounded-x social_googleplus" data-original-title="Google Plus" href="#"></a></li>
                            <li><a class="rounded-x social_linkedin" data-original-title="Linkedin" href="#"></a></li>
                        </ul>-->
                        <a href="/ostim/sanalfabrika" class="btn btn-block "><img style="height:50px;" src="/dist/img/ostim_logo_en.png"> <img style="height:50px;" src="/onyuz/One-Page/assets/img/logo/header_logo.png"> </a>

                        <h4><?php echo $this->translate('Please enter your preffered password') ?></h4>                    
                        <!--<p><?php echo $this->translate("Don't Have Account? Click") ?><a class="color-green" href="/ostim/sanalfabrika/registration"><?php echo $this->translate('Sign Up') ?></a> <?php echo $this->translate('to registration.') ?></p>-->            
                    </div>

                    <div class="input-group margin-bottom-20">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input type="password" id="password" name="password" class="form-control validate[required,minSize[8],maxSize[20]]" placeholder="Password">                    
                        <span class="input-group-addon" onclick="showPassword()"><i class="icon-eye"></i></span>
                    </div>
                    <div class="input-group margin-bottom-20">
                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input type="password" id="password_repeat" name="password_repeat" class="form-control validate[required,minSize[8],maxSize[20]]" data-prompt-position="bottomLeft" placeholder="Repeat Password">                    
                        <span class="input-group-addon" onclick="showPassword()"><i class="icon-eye"></i></span>
                    </div>
                    <hr>

                    <!--                <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> 
                                            <p><?php echo $this->translate("Always stay signed in") ?></p>
                                        </label>            
                                    </div>-->

                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <button type="button" class="btn-u btn-block" onclick="return confirmPass();"><?php echo $this->translate("Confirm") ?></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!--End Reg Block-->
    </div><!--/container-->
    <!--=== End Content Part ===-->
</body>

</html>