<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>


<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<div class="wrapper">
    <!--=== Header ===-->    
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="index-2.html">
                <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/logo/header_logo.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul style="background: #ddd;
                    padding: 10px;" class="loginbar pull-right">
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('Languages') ?> </a>
                        <i class="fa fa-globe"></i>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>   
                    <li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><?php echo $this->translate('Log out') ?></a></li>     
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="#body"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('About Us') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Services') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="#body">
                                    <?php echo $this->translate('OSTIM Services') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="#news"><?php echo $this->translate('News') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contacts') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Submenus') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="#body"><?php echo $this->translate('Home') ?></a>
                            </li>
                            <li class="page-scroll">
                                <a href="../index-2.html"><?php echo $this->translate('Main') ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->


    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 class="pull-left"><i class="fa fa-comments"></i><?php echo $this->translate('Comments') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', 
                            array('action' => 'index')); ?>">
                        <?php echo $this->translate('Home') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', 
                            array('action' => 'userprofile')); ?>">
                        <?php echo $this->translate('User Profile') ?>
                    </a>
                </li>
                <li class="active"><?php echo $this->translate('Comments') ?></li>   
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->


    <!--=== Profile ===-->
    <div class="container content profile">
        
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo $this->basePath('onyuz/standard/assets/img/team/img32-md.jpg')?>" alt="">

                <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                    <li class="list-group-item">
                        <a href="userprofile"><i class="fa fa-bar-chart-o"></i> <?php echo $this->translate('Overall')?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="userprofilepersonal"><i class="fa fa-user"></i> <?php echo $this->translate('Profile')?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="userprofileusers"><i class="fa fa-group"></i> <?php echo $this->translate('Users')?></a>
                    </li>                                        
                    <li class="list-group-item">
                        <a href="userprofileprojects"><i class="fa fa-cubes"></i> <?php echo $this->translate('My Projects')?></a>
                    </li>
                    <li class="list-group-item active">
                        <a href="userprofilecomments"><i class="fa fa-comments"></i> <?php echo $this->translate('Comments')?></a>
                    </li>                                        
                    <li class="list-group-item">
                        <a href="userprofilehistory"><i class="fa fa-history"></i> <?php echo $this->translate('History')?></a>
                    </li>                                       
<!--                    <li class="list-group-item">
                        <a href="userprofilesettings"><i class="fa fa-cog"></i> <?php echo $this->translate('Settings')?></a>
                    </li> -->
                </ul>   

                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bar-chart-o"></i> <?php echo $this->translate('Task Progress')?></h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <h3 class="heading-xs">Web Design <span class="pull-right">92%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 92%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="92" role="progressbar" class="progress-bar progress-bar-u">
                    </div>
                </div>
                <h3 class="heading-xs">Unify Project <span class="pull-right">85%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 85%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="85" role="progressbar" class="progress-bar progress-bar-blue">
                    </div>
                </div>
                <h3 class="heading-xs">Sony Corporation <span class="pull-right">64%</span></h3>
                <div class="progress progress-u progress-xxs margin-bottom-40">
                    <div style="width: 64%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="64" role="progressbar" class="progress-bar progress-bar-dark">
                    </div>
                </div>

                <hr>

                <!--Notification-->
                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> <?php echo $this->translate('Notification')?></h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <ul class="list-unstyled mCustomScrollbar margin-bottom-20" data-mcs-theme="minimal-dark">
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-red icon-line icon-envelope"></i>
                        <div class="overflow-h">
                            <span><strong>Albert Heller</strong> <?php echo $this->translate('has sent you email.')?></span>
                            <small>Two <?php echo $this->translate('minutes')?> <?php echo $this->translate('ago')?></small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> <?php echo $this->translate('started following you.')?></span>
                            <small>Today 18:25 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                        <div class="overflow-h">
                            <span><strong>Natasha Kolnikova</strong> <?php echo $this->translate('accepted your invitation.')?></span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img1.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Mikel Andrews</strong> <?php echo $this->translate('commented on your Timeline.')?></span>
                            <small>23/12 11:01 am</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                        <div class="overflow-h">
                            <span><strong>Bruno Js.</strong> added you to group chating.</span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> <?php echo $this->translate('changed profile picture.')?></span>
                            <small>23/12 15:15 pm</small>
                        </div>    
                    </li>
                </ul>  
            </div>
            <!--End Left Sidebar-->

            <!-- Profile Content -->                
            <div class="col-md-9">
                <div class="profile-body">
                    <div class="panel panel-profile">
                        <div class="panel-heading overflow-h">
                            <h2 class="panel-title heading-sm pull-left"><i class="fa fa-comments"></i><?php echo $this->translate('Users Comments')?></h2>
                            <a href="#"><i class="fa fa-cog pull-right"></i></a>
                        </div>
                        <div class="panel-body margin-bottom-50">
                            <div class="media media-v2">
                                <a class="pull-left" href="#">
                                    <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img2.jpg')?>" alt="">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">
                                        <strong><a href="#">Eva Nelson</a></strong> @EvaNelson
                                        <small><?php echo $this->translate('About')?> <?php echo $this->translate('an hour ago')?> </small>
                                    </h4>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada rhoncus tellus blandit facilisis. Morbi faucibus eros facilisis vulputate mollis. Mauris sodales ante lorem, sed fringilla orci rhoncus ac. Donec sit amet eros at libero egestas interdum non quis libero.</p>
                                    <ul class="list-inline results-list pull-left">
                                        <li><a href="#">25 <?php echo $this->translate('Links')?></a></li>
                                        <li><a href="#">10 <?php echo $this->translate('Share')?></a></li>
                                    </ul>    
                                    <ul class="list-inline pull-right">
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                    </ul>
                                </div>
                            </div><!--/end media media v2--> 
                            <div class="media media-v2 margin-bottom-20">
                                <a class="pull-left" href="#">
                                    <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img3.jpg')?>" alt="">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">
                                        <strong><a href="#">Frank Lennon</a></strong> @FLennon 
                                        <small>4 <?php echo $this->translate('hours')?> <?php echo $this->translate('hours')?> <?php echo $this->translate('ago')?></small>
                                    </h4>
                                    <p>I'm incredibly excited to announce that I am joining the amazing <a href="#">@Unify</a> team. To be in touch with the latest update, Sign up and get your own Account page fee free :) Like mine: <a href="#">http://www.unify.com/flennon</a></p>
                                    <ul class="list-inline results-list pull-left">
                                        <li><a href="#">5 <?php echo $this->translate('Likes')?></a></li>
                                        <li><a href="#">1 <?php echo $this->translate('Share')?></a></li>
                                    </ul>
                                    <ul class="list-inline pull-right">
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                    </ul>

                                    <div class="clearfix"></div>
                                    
                                    <div class="media media-v2">
                                        <a class="pull-left" href="#">
                                            <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img7.jpg')?>" alt="">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading">
                                                <strong><a href="#">Edward Rooster</a></strong> @EdwardRooster 
                                                <small>5 <?php echo $this->translate('hours')?> <?php echo $this->translate('ago')?></small>
                                            </h4>
                                            <p>Welcome to Board! :) Your journey starts here. Wish you all the best!</p>
                                            <ul class="list-inline results-list pull-left">
                                                <li><a href="#">0 <?php echo $this->translate('Likes')?></a></li>
                                                <li><a href="#">0 <?php echo $this->translate('Share')?></a></li>
                                            </ul>
                                            <ul class="list-inline pull-right">
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>    
                            </div><!--/end media media v2-->
                            <button type="button" class="btn-u btn-u-default btn-block"><?php echo $this->translate('Load More')?></button>
                        </div>
                    </div>    
                    
                    <div class="panel panel-profile">
                        <div class="panel-heading overflow-h">
                            <h2 class="panel-title heading-sm pull-left"><i class="fa fa-comments"></i><?php echo $this->translate('Projects Comments')?></h2>
                            <a href="#"><i class="fa fa-cog pull-right"></i></a>
                        </div>
                        <div class="panel-body">
                            <div class="media media-v2 margin-bottom-20">
                                <a class="pull-left" href="#">
                                    <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">
                                        <strong><a href="#">Lee Parker</a></strong> @LeePark 
                                        <small>12 <?php echo $this->translate('hours')?> <?php echo $this->translate('ago')?></small>
                                    </h4>
                                    <p>Pellentesque scelerisque vitae mi quis sollicitudin. Sed pellentesque nulla eleifend hendrerit rhoncus. Aenean rhoncus imperdiet pretium. Nunc vitae egestas eros, vel fringilla arcu. Duis vel libero sit amet metus faucibus venenatis in sit amet nisl. Fusce imperdiet enim risus. Cras orci velit, tempor dignissim ante eget, rhoncus hendrerit nisi. </p>
                                    <ul class="list-inline img-uploaded">
                                        <li><img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img12.jpg')?>" alt=""></li>
                                        <li><img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img3.jpg')?>" alt=""></li>
                                        <li><img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img16.jpg')?>" alt=""></li>
                                    </ul>
                                    <ul class="list-inline results-list pull-left">
                                        <li><a href="#">7 <?php echo $this->translate('Likes')?></a></li>
                                        <li><a href="#">2 <?php echo $this->translate('Share')?></a></li>
                                    </ul>
                                    <ul class="list-inline pull-right">
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                        <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                    </ul>

                                    <div class="clearfix"></div>
                                    
                                    <div class="media media-v2">
                                        <a class="pull-left" href="#">
                                            <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img7.jpg')?>" alt="">
                                        </a>
                                        <div class="media-body">
                                            <h4 class="media-heading">
                                                <strong><a href="#">Edward Rooster</a></strong> @EdwardRooster 
                                                <small>7 <?php echo $this->translate('hours')?> <?php echo $this->translate('ago')?></small>
                                            </h4>
                                            <p>How was trip?</p>
                                            <ul class="list-inline results-list pull-left">
                                                <li><a href="#">0 <?php echo $this->translate('Likes')?></a></li>
                                                <li><a href="#">0 <?php echo $this->translate('Share')?></a></li>
                                            </ul>
                                            <ul class="list-inline pull-right">
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                                <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                            </ul>

                                            <div class="clearfix"></div>
                                            
                                            <div class="media media-v2">
                                                <a class="pull-left" href="#">
                                                    <img class="media-object rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                                                </a>
                                                <div class="media-body">
                                                    <h4 class="media-heading">
                                                        <strong><a href="#">Lee Parker</a></strong> @LeePark 
                                                        <small>9 <?php echo $this->translate('hours')?> <?php echo $this->translate('ago')?></small>
                                                    </h4>
                                                    <p>Amazing!</p>
                                                    <ul class="list-inline results-list pull-left">
                                                        <li><a href="#">0 <?php echo $this->translate('Likes')?></a></li>
                                                        <li><a href="#">0 <?php echo $this->translate('Share')?></a></li>
                                                    </ul>
                                                    <ul class="list-inline pull-right">
                                                        <li><a href="#"><i class="expand-list rounded-x fa fa-reply"></i></a></li>
                                                        <li><a href="#"><i class="expand-list rounded-x fa fa-heart"></i></a></li>
                                                        <li><a href="#"><i class="expand-list rounded-x fa fa-retweet"></i></a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>    
                                </div>
                            </div><!--/end media media v2-->
                            <button type="button" class="btn-u btn-u-default btn-block"><?php echo $this->translate('Load More')?></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Profile Content -->                
        </div>
        
    </div><!--/container-->    
    <!--=== End Profile ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="index-2.html"><img id="logo-footer" class="footer-logo" 
                                                    src="<?php echo $this->basePath('onyuz/One-Page/assets/img/logo/footer_logo.png') ?>" 
                                                    alt=""></a>
                        <p><?php
                            echo $this->translate('OSB Imalat is a temporary alliance of '
                                    . 'businesses that come together to share skills or core competencies and resources '
                                    . 'in order to better respond to business opportunities, and whose cooperation is '
                                    . 'supported by computer networks.')
                            ?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('Latest Posts') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('Latest News about OSB Imalat') ?></a>
                                    <small><?php echo $this->translate('February') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('OSTIM Clusters News') ?></a>
                                    <small><?php echo $this->translate('January') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('New Project Calls') ?></a>
                                    <small><?php echo $this->translate('December') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Useful Links') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <!--<li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('Ostim Organized Industrial Zone') ?></a><i class="fa fa-angle-right"></i></li>-->
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('Turkish Ministry of SIT') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('TUBITAK') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('KOSGEB') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Contact Us') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                             <br />
                            Ankara<br />
                            Turkey <br />
                            <?php echo $this->translate('Phone') ?> :<br />
                            <?php echo $this->translate('Fax') ?>:    <br />
                            <?php echo $this->translate('Email') ?>: <a href="mailto:info@osbimalat.com.tr" class="">info@osbimalat.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('All Rights Reserved.') ?>
                            <a href="#"><?php echo $this->translate('Privacy Policy') ?></a> | <a href="#"><?php echo $this->translate('Terms of Service') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/osbimalat/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/osbimalat" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/osbimalat/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/osbimalat" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>        
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->

