<!DOCTYPE html>
<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>


<!--=== Style Switcher ===-->    
<i class="style-switcher-btn fa fa-cogs hidden-xs"></i>
<div class="style-switcher animated fadeInRight">
    <div class="style-swticher-header">
        <div class="style-switcher-heading">Style Switcher</div>            
        <div class="theme-close"><i class="icon-close"></i></div>
    </div>

    <div class="style-swticher-body">
        <!-- Theme Colors -->
        <div class="style-switcher-heading">Theme Colors</div>
        <ul class="list-unstyled">
            <li class="theme-default theme-active" data-style="default" data-header="light"></li>
            <li class="theme-blue" data-style="blue" data-header="light"></li>
            <li class="theme-orange" data-style="orange" data-header="light"></li>
            <li class="theme-red" data-style="red" data-header="light"></li>
            <li class="theme-light" data-style="light" data-header="light"></li>
            <li class="theme-purple last" data-style="purple" data-header="light"></li>
            <li class="theme-aqua" data-style="aqua" data-header="light"></li>
            <li class="theme-brown" data-style="brown" data-header="light"></li>
            <li class="theme-dark-blue" data-style="dark-blue" data-header="light"></li>
            <li class="theme-light-green" data-style="light-green" data-header="light"></li>
            <li class="theme-dark-red" data-style="dark-red" data-header="light"></li>
            <li class="theme-teal last" data-style="teal" data-header="light"></li>
        </ul>

        <!-- Theme Skins -->
        <div class="style-switcher-heading">Theme Skins</div>
        <div class="row no-col-space margin-bottom-20 skins-section">
            <div class="col-xs-6">
                <button data-skins="default" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn handle-skins-btn">Light</button>
            </div>
            <div class="col-xs-6">
                <button data-skins="dark" class="btn-u btn-u-xs btn-u-dark btn-block skins-btn">Dark</button>
            </div>
        </div>            

        <hr>

        <!-- Layout Styles -->
        <div class="style-switcher-heading">Layout Styles</div>
        <div class="row no-col-space margin-bottom-20">
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block active-switcher-btn wide-layout-btn">Wide</a>                
            </div>
            <div class="col-xs-6">
                <a href="javascript:void(0);" class="btn-u btn-u-xs btn-u-dark btn-block boxed-layout-btn">Boxed</a>                
            </div>
        </div>            

        <hr>

        <!-- Theme Type -->
        <div class="style-switcher-heading">Theme Types and Versions</div>
        <div class="row no-col-space margin-bottom-10">
            <div class="col-xs-6">
                <a href="Shop-UI/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Shop UI <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="One-Page/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">One Page <small class="dp-block">Template</small></a>
            </div>
        </div>           

        <div class="row no-col-space">
            <div class="col-xs-6">
                <a href="Blog/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">Blog <small class="dp-block">Template</small></a>
            </div>
            <div class="col-xs-6">
                <a href="RTL/index.html" class="btn-u btn-u-xs btn-u-dark btn-block">RTL <small class="dp-block">Version</small></a>
            </div>
        </div>           
    </div>
</div><!--/style-switcher-->
<!--=== End Style Switcher ===-->    

<div class="wrapper">
    <!--=== Header ===-->    
    <div class="header">
        <div class="container">
            <!-- Logo -->
            <a class="logo" href="index-2.html">
                <img src="<?php echo $this->basePath('onyuz/One-Page/assets/img/logo/header_logo.png') ?>" alt="Logo">
            </a>
            <!-- End Logo -->

            <!-- Topbar -->
            <div class="topbar">
                <ul style="background: #ddd;
                    padding: 10px;" class="loginbar pull-right">
                    <li class="hoverSelector">
                        <a><?php echo $this->translate('Languages') ?> </a>
                        <i class="fa fa-globe"></i>
                        <ul id='topLanguageBar' class="languages hoverSelectorBlock">                                    
                        </ul>
                    </li>
                    <li class="topbar-devider"></li>   
                    <li><a href="page_faq.html"><?php echo $this->translate('Help') ?></a></li>  
                    <li class="topbar-devider"></li>      
                    <li><a href="<?php echo $this->url('login', array('action' => 'logout')); ?>"><?php echo $this->translate('Log out') ?></a></li>    
                </ul>
            </div>
            <!-- End Topbar -->

            <!-- Toggle get grouped for better mobile display -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bars"></span>
            </button>
            <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse menu-xs navbar-responsive-collapse" >
            <div class="container">
                <ul class="nav navbar-nav " style="font-size: 10px;">
                    <li class="page-scroll home">
                        <a href="#body"><?php echo $this->translate('Home') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about"><?php echo $this->translate('About Us') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Services') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll"><a href="#body">
                                    <?php echo $this->translate('OSTIM Services') ?></a>
                            </li>
                        </ul>
                    </li>
                    <li class="page-scroll">
                        <a href="#news"><?php echo $this->translate('News') ?></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact"><?php echo $this->translate('Contacts') ?></a>
                    </li>
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate('Submenus') ?>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="page-scroll">
                                <a href="#body"><?php echo $this->translate('Home') ?></a>
                            </li>
                            <li class="page-scroll">
                                <a href="../index-2.html"><?php echo $this->translate('Main') ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div><!--/end container-->
        </div><!--/navbar-collapse-->
    </div>
    <!--=== End Header ===-->


    <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <!--<div style='background: #FAF8F0;' class="container">--> 
        <div style='background: #E0EDDF;' class="container">
            <h1 class="pull-left"><i class="fa fa-user"></i><?php echo $this->translate('Projects') ?></h1>
            <ul class="pull-right breadcrumb">                        
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', 
                            array('action' => 'index')); ?>">
                        <?php echo $this->translate('Home') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('sanalfabrika', 
                            array('action' => 'userprofile')); ?>">
                        <?php echo $this->translate('User Profile') ?>
                    </a>
                </li>
                <li class="active"><?php echo $this->translate('Projects') ?></li> 
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->


    <!--=== Profile ===-->
    <div class="container content profile">
        
        <div class="row">
            <!--Left Sidebar-->
            <div class="col-md-3 md-margin-bottom-40">
                <img class="img-responsive profile-img margin-bottom-20" src="<?php echo $this->basePath('onyuz/standard/assets/img/team/img32-md.jpg')?>" alt="">

                <ul class="list-group sidebar-nav-v1 margin-bottom-40" id="sidebar-nav-1">
                    <li class="list-group-item">
                        <a href="userprofile"><i class="fa fa-bar-chart-o"></i> <?php echo $this->translate('Overall')?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="userprofilepersonal"><i class="fa fa-user"></i> <?php echo $this->translate('Profile')?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="userprofileusers"><i class="fa fa-group"></i> <?php echo $this->translate('Users')?></a>
                    </li>                                        
                    <li class="list-group-item active">
                        <a href="userprofileprojects"><i class="fa fa-cubes"></i> <?php echo $this->translate('My Projects')?></a>
                    </li>
                    <li class="list-group-item">
                        <a href="userprofilecomments"><i class="fa fa-comments"></i> <?php echo $this->translate('Comments')?></a>
                    </li>                                        
                    <li class="list-group-item">
                        <a href="userprofilehistory"><i class="fa fa-history"></i> <?php echo $this->translate('History')?></a>
                    </li>                                       
<!--                    <li class="list-group-item">
                        <a href="userprofilesettings"><i class="fa fa-cog"></i> <?php echo $this->translate('Settings')?></a>
                    </li> -->
                </ul>   

                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bar-chart-o"></i> Task Progress</h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <h3 class="heading-xs">Web Design <span class="pull-right">92%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 92%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="92" role="progressbar" class="progress-bar progress-bar-u">
                    </div>
                </div>
                <h3 class="heading-xs">Unify Project <span class="pull-right">85%</span></h3>
                <div class="progress progress-u progress-xxs">
                    <div style="width: 85%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="85" role="progressbar" class="progress-bar progress-bar-blue">
                    </div>
                </div>
                <h3 class="heading-xs">Sony Corporation <span class="pull-right">64%</span></h3>
                <div class="progress progress-u progress-xxs margin-bottom-40">
                    <div style="width: 64%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="64" role="progressbar" class="progress-bar progress-bar-dark">
                    </div>
                </div>

                <hr>

                <!--Notification-->
                <div class="panel-heading-v2 overflow-h">
                    <h2 class="heading-xs pull-left"><i class="fa fa-bell-o"></i> Notification</h2>
                    <a href="#"><i class="fa fa-cog pull-right"></i></a>
                </div>
                <ul class="list-unstyled mCustomScrollbar margin-bottom-20" data-mcs-theme="minimal-dark">
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-red icon-line icon-envelope"></i>
                        <div class="overflow-h">
                            <span><strong>Albert Heller</strong> has sent you email.</span>
                            <small>Two minutes ago</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> started following you.</span>
                            <small>Today 18:25 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-yellow icon-line fa fa-bolt"></i>
                        <div class="overflow-h">
                            <span><strong>Natasha Kolnikova</strong> accepted your invitation.</span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img1.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Mikel Andrews</strong> commented on your Timeline.</span>
                            <small>23/12 11:01 am</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <i class="icon-custom icon-sm rounded-x icon-bg-blue icon-line fa fa-comments"></i>
                        <div class="overflow-h">
                            <span><strong>Bruno Js.</strong> added you to group chating.</span>
                            <small>Yesterday 1:07 pm</small>
                        </div>    
                    </li>
                    <li class="notification">
                        <img class="rounded-x" src="<?php echo $this->basePath('onyuz/standard/assets/img/testimonials/img6.jpg')?>" alt="">
                        <div class="overflow-h">
                            <span><strong>Taylor Lee</strong> changed profile picture.</span>
                            <small>23/12 15:15 pm</small>
                        </div>    
                    </li>
                </ul>    
                
            </div>
            <!--End Left Sidebar-->

            <!-- Profile Content -->            
            <div class="col-md-9">
                <div class="profile-body">
                    <!--Projects-->
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="easy-block-v1">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img12.jpg')?>" alt="">
                                <div class="easy-block-v1-badge rgba-red">Web Design</div>
                            </div>    
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Rigging in Autodesk 3Ds Max</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?>  <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 02, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">77%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="77" aria-valuemin="0" aria-valuemax="100" style="width: 77%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>12%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>17%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>25</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">25</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">32</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">77</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="service-or easy-block-v2 no-margin-bottom">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img16.jpg')?>" alt="">
                                <div class="easy-bg-v2 rgba-default"><?php echo $this->translate('Aviation')?></div>
                            </div>
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Getting Started Photography</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?> <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 07, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">92%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="92" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>45%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>58%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>5</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">45</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">90</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">84</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                </ul>
                            </div>
                        </div>
                    </div><!--/end row-->
                    <!--End Projects-->

                    <hr>

                    <!--Projects-->
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="easy-block-v1">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img17.jpg')?>" alt="">
                                <div class="easy-block-v1-badge rgba-purple">Graphic Design</div>
                            </div>    
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Rigging in Autodesk 3Ds Max</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?>  <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 02, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">77%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="77" aria-valuemin="0" aria-valuemax="100" style="width: 77%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>12%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>17%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>25</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">25</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">32</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">77</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="service-or easy-block-v2 no-margin-bottom">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img18.jpg')?>" alt="">
                                <div class="easy-bg-v2 rgba-blue">Nokia</div>
                            </div>
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Getting Started Photography</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?>  <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 07, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">92%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="92" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>45%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>58%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>5</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">45</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">90</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">84</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                </ul>
                            </div>
                        </div>
                    </div><!--/end row-->
                    <!--End Projects-->

                    <hr>

                    <!--Projects-->
                    <div class="row margin-bottom-30">
                        <div class="col-sm-6">
                            <div class="easy-block-v1">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img19.jpg')?>" alt="">
                                <div class="easy-block-v1-badge rgba-aqua">Unify Project</div>
                            </div>    
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Rigging in Autodesk 3Ds Max</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?>  <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 02, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">77%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="77" aria-valuemin="0" aria-valuemax="100" style="width: 77%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>12%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>17%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>25</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">25</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">32</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">77</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                    <li><i class="color-green fa fa-star-o"></i></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="service-or easy-block-v2 no-margin-bottom">
                                <img class="img-responsive" src="<?php echo $this->basePath('onyuz/standard/assets/img/main/img20.jpg')?>" alt="">
                                <div class="easy-bg-v2 rgba-yellow">Sony</div>
                            </div>
                            <div class="projects">
                                <h2><a class="color-dark" href="#">Getting Started Photography</a></h2>
                                <ul class="list-unstyled list-inline blog-info-v2">
                                    <li><?php echo $this->translate('By:')?>  <a class="color-green" href="userprofile">User Name</a></li>
                                    <li><i class="fa fa-clock-o"></i> Jan 07, 2013</li>
                                </ul>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry printing. Donec non dignissim eros. Mauris faucibus turpis volutpat sagittis rhoncus. Pellentesque et rhoncus sapien, sed ullamcorper justo.</p>
                                <br>
                                <h3 class="heading-xs"><?php echo $this->translate('Project Completeness')?> <span class="pull-right">92%</span></h3>
                                <div class="progress progress-u progress-xxs">
                                    <div class="progress-bar progress-bar-u" role="progressbar" aria-valuenow="92" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                    </div>
                                </div>
                                <ul class="list-inline blog-info-v2">
                                    <li>
                                        <strong>45%</strong>
                                        <span><?php echo $this->translate('Funded')?></span>
                                    </li>
                                    <li>
                                        <strong>58%</strong>
                                        <span><?php echo $this->translate('Pludged')?></span>
                                    </li>
                                    <li>
                                        <strong>5</strong>
                                        <span><?php echo $this->translate('days to go')?></span>
                                    </li>
                                </ul>
                            </div>    
                            <div class="project-share">
                                <ul class="list-inline comment-list-v2 pull-left">
                                    <li><i class="fa fa-eye"></i> <a href="#">45</a></li>
                                    <li><i class="fa fa-comments"></i> <a href="#">90</a></li>
                                    <li><i class="fa fa-retweet"></i> <a href="#">84</a></li>
                                </ul>    
                                <ul class="list-inline star-vote pull-right">
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star"></i></li>
                                    <li><i class="color-green fa fa-star-half-o"></i></li>
                                </ul>
                            </div>
                        </div>
                    </div><!--/end row-->
                    <!--End Projects-->
                    <button type="button" class="btn-u btn-u-default btn-u-sm btn-block">Load More</button>
                </div>
            </div>
            <!-- End Profile Content -->            
        </div>
        
    </div><!--/container-->    
    <!--=== End Profile ===-->

    <!--=== Footer Version 1 ===-->
    <div class="footer-v1">
        <div class="footer">
            <div class="container">
                <div class="row">
                    <!-- About -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <a href="index-2.html"><img id="logo-footer" class="footer-logo" 
                                                    src="<?php echo $this->basePath('onyuz/One-Page/assets/img/logo/footer_logo.png') ?>" 
                                                    alt=""></a>
                        <p><?php
                            echo $this->translate('OSB Imalat is a temporary alliance of '
                                    . 'businesses that come together to share skills or core competencies and resources '
                                    . 'in order to better respond to business opportunities, and whose cooperation is '
                                    . 'supported by computer networks.')
                            ?></p>
                    </div><!--/col-md-3-->
                    <!-- End About -->

                    <!-- Latest -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="posts">
                            <div class="headline"><h2><?php echo $this->translate('Latest Posts') ?></h2></div>
                            <ul class="list-unstyled latest-list">
                                <li>
                                    <a href="#"><?php echo $this->translate('Latest News about OSB Imalat') ?></a>
                                    <small><?php echo $this->translate('February') ?> 8, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('OSTIM Clusters News') ?></a>
                                    <small><?php echo $this->translate('January') ?> 23, 2016</small>
                                </li>
                                <li>
                                    <a href="#"><?php echo $this->translate('New Project Calls') ?></a>
                                    <small><?php echo $this->translate('December') ?> 15, 2016</small>
                                </li>
                            </ul>
                        </div>
                    </div><!--/col-md-3-->  
                    <!-- End Latest --> 

                    <!-- Link List -->
                    <div class="col-md-3 md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Useful Links') ?></h2></div>
                        <ul class="list-unstyled link-list">
                            <!--<li><a href="http://www.ostim.org.tr/"><?php echo $this->translate('Ostim Organized Industrial Zone') ?></a><i class="fa fa-angle-right"></i></li>-->
                            <li><a href="http://www.sanayi.gov.tr/"><?php echo $this->translate('Turkish Ministry of SIT') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="https://www.tubitak.gov.tr/"><?php echo $this->translate('TUBITAK') ?></a><i class="fa fa-angle-right"></i></li>
                            <li><a href="http://www.kosgeb.gov.tr/"><?php echo $this->translate('KOSGEB') ?></a><i class="fa fa-angle-right"></i></li>
                            <!--<li><a href="#"><?php echo $this->translate('') ?></a><i class="fa fa-angle-right"></i></li>-->
                        </ul>
                    </div><!--/col-md-3-->
                    <!-- End Link List -->                    

                    <!-- Address -->
                    <div class="col-md-3 map-img md-margin-bottom-40">
                        <div class="headline"><h2><?php echo $this->translate('Contact Us') ?></h2></div>                         
                        <address class="md-margin-bottom-40">
                             <br />
                            Ankara<br />
                            Turkey <br />
                            <?php echo $this->translate('Phone') ?> :<br />
                            <?php echo $this->translate('Fax') ?>:    <br />
                            <?php echo $this->translate('Email') ?>: <a href="mailto:info@osbimalat.com.tr" class="">info@osbimalat.com.tr</a>
                        </address>
                    </div><!--/col-md-3-->
                    <!-- End Address -->
                </div>
            </div> 
        </div><!--/footer-->

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">                     
                        <p>
                            2016 &copy; <?php echo $this->translate('All Rights Reserved.') ?>
                            <a href="#"><?php echo $this->translate('Privacy Policy') ?></a> | <a href="#"><?php echo $this->translate('Terms of Service') ?></a>
                        </p>
                    </div>

                    <!-- Social Links -->
                    <div class="col-md-6">
                        <ul class="footer-socials list-inline">
                            <li>
                                <a href="https://www.facebook.com/osbimalat/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype">
                                    <i class="fa fa-skype"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://plus.google.com/osbimalat" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/ostim-osb-2b94b847" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Linkedin">
                                    <i class="fa fa-linkedin"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/osbimalat/" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/osbimalat" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Social Links -->
                </div>
            </div> 
        </div><!--/copyright-->
    </div>        
    <!--=== End Footer Version 1 ===-->
</div><!--/wrapper-->

