


<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from cdn1.crumina.net/html-seosight/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 12 Oct 2016 08:35:32 GMT -->
    <!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
    <head lang="en">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Seosight - Index Page</title>

        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/fonts.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/crumina-fonts.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/normalize.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/grid.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/styles.css')?>">
        
        <!-- Web Fonts  -->
        <link href="<?php echo $this->basePath('comics_docs/fonts.googleapis.com/cssfb2f.css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light')?>" rel="stylesheet" type="text/css">


        <!--Plugins styles-->

        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/jquery.mCustomScrollbar.min.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/swiper.min.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/primary-menu.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('comics_docs/css/magnific-popup.css')?>">


    </head>


    <body class=" ">


        <?php echo $this->content; ?>


        <?php /* echo $this->inlineScript() */ ?>
        <!-- JS Script -->

        <script src="<?php echo $this->basePath('comics_docs/js/jquery-2.1.4.min.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/crum-mega-menu.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/swiper.jquery.min.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/theme-plugins.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/main.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/form-actions.js')?>"></script>

        <script src="<?php echo $this->basePath('comics_docs/js/velocity.min.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/ScrollMagic.min.js')?>"></script>
        <script src="<?php echo $this->basePath('comics_docs/js/animation.velocity.min.js')?>"></script>


        <!-- ...end JS Script -->

    </body>

    <!-- Mirrored from cdn1.crumina.net/html-seosight/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 12 Oct 2016 08:36:36 GMT -->
</html>